feat(react): useClientEffect 훅 추가
modern-agile-team/modern-kit pull request #139
Opened 2024-05-19 06:40 UTC by soonki-98

## Overview

- 클라이언트 환경에서만 실행되는 `useClientEffect` 훅 추가
- 테스트 작성
  1. 서버 환경에서는 콜백이 실행되지 않아야 한다.
  2. 클라이언트 환경에서는 콜백이 실행되어야 한다.
  3. 클라이언트 환경에서는 의존성 배열에 따라 콜백이 실행되어야 한다.
  4. 의존성 배열이 비어있으면 빈 배열을 사용해야 한다.
 - mdx 문서 작성

## PR Checklist
- [x] All tests pass.
- [x] All type checks pass.
- [x] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-05-19 07:21 UTC, ssi02014 requested changes
useClientEffect 좋은 훅 같습니다!
추가 의견을 코멘트로 남겼습니다 감사합니다!

2024-05-19 07:21 UTC, ssi02014 commented on packages/react/src/hooks/useClientEffect/useClientEffect.spec.tsx
> +};
컴포넌트를 생성하지 않고 renderHook으로 테스트를 진행할 수 있을 것 같습니다 :) 
아래는 테스트 예제입니다.
```tsx
describe('useClientEffect', () => {
  const isServer = ModernUtilKit.isServer as Mock;

  it('test', () => {
    isServer.mockReturnValue(false);

    const test = vi.fn();
    const { rerender } = renderHook(
      ({ callback, deps }) => useClientEffect(callback, deps),
      {
        initialProps: {
          callback: test,
          deps: ['foo'] as React.DependencyList,
        },
      }
    );

    expect(test).toBeCalledTimes(1);

    rerender({ callback: test, deps: ['bar'] });

    expect(test).toBeCalledTimes(2);
  });
});
```

2024-05-19 07:24 UTC, ssi02014 commented on packages/react/src/hooks/useClientEffect/index.ts
> +};
deps의 경우에도 내부 요소중에 참조형이 있을 경우 무한 호출 가능성이 있네요.
usePreservedState(deps)로 매핑하면 안정적일 것 같습니다 ~!

```tsx
const preservedCallback = usePreservedCallback(callback);
const preservedDepts = usePreservedState(deps);

  useEffect(() => {
    if (isServer()) return;
    preservedCallback();
  }, [...preservedDepts, preservedCallback]);
```

2024-05-19 07:31 UTC, ssi02014 commented
@soonki-98 생각해보니.. useEffect는 클라이언트 환경에서만 실행되서 useEffect라면 isServer를 검증 할 필요가 없을 것 같네요..?

2024-05-19 07:33 UTC, ssi02014 commented
cc. @Sangminnn

2024-05-19 07:37 UTC, ssi02014 commented on packages/react/src/hooks/useClientEffect/index.ts
> +};
@soonki-98 deps 부분은 제가 좀 잘못생각한 것 같습니다 기존과 같이 냅둬도 상관없겠네요 😞

2024-05-19 13:17 UTC, Sangminnn commented on packages/react/src/hooks/useClientEffect/useClientEffect.spec.tsx
> +};
저도 너무 좋은 훅으로 보입니다! 작업해주시느라 너무 고생 많으셨습니다 👍👍👍
테스팅방식은 작성해주신 방식도 좋았으나 hook이다보니 hook testing으로 하는 방법이 더 자연스럽게 느껴졌네요 😄

2024-05-21 10:08 UTC, ssi02014 commented
https://github.com/modern-agile-team/modern-kit/pull/139#issuecomment-2119134773
@soonki-98 제 의견을 위 코멘트로 남겼습니다 확인해주시고 피드백 부탁드립니다 😄

2024-05-21 11:32 UTC, Sangminnn commented
헉 저도 @ssi02014 께서 남겨주신 의견을 보고 다시 생각해보니 맞군요 ..! 😶‍🌫️ (역할은 다르지만 isomorphicEffect와도 살짝 혼동이 되었었네요!) 
단순한 Effect의 수행이라면 클라이언트에서의 실행이 보장될것으로 예상됩니다! 🤔

2024-05-26 15:51 UTC, ssi02014 commented
해당 PR은 추가 피드백이 없어서 우선 Close 하겠습니다..!
추후에 추가 의견이 있으시다면 그때 PR을 다시 열어주시면 감사드립니다 🙏 cc. @soonki-98 @Sangminnn

2024-05-26 15:52 UTC, closed without merging