feat(utils): deepCopy 순환참조 대응 및 Date, Regex 테스트 코드 추가
modern-agile-team/modern-kit pull request #151
Opened 2024-05-21 13:29 UTC by hoonloper

## Overview

- 자신을 참조하는 데이터를 deepCopy했을 때 maximum call stack 이슈가 발생하던 것을 해결했습니다.
- `Date`, `Regex` 타입의 간단한 깊은 복사 테스트 코드를 추가했습니다.
- 복사된 값을 할당하는 변수명이 동사로 되어있어 수정했습니다.

![image](https://github.com/modern-agile-team/modern-kit/assets/78959175/0a3fa7dd-18f5-4551-92b2-53854e0e2ac8)

## PR Checklist
- [x] All tests pass.
- [x] All type checks pass.
- [ ] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-05-21 15:05 UTC, ssi02014 requested changes
@hoonloper `순환 참조`에 대한 처리를 고려하지 못했는데 좋은 의견 주셔서 너무 감사합니다!
lodash와 같은 라이브러리의 cloneDeep도 해당 문제를 잘 대응하고 있기 때문에 해당 작업이 너무 좋은 것 같습니다! 🤗
몇 가지만 작은 의견만 드려봅니다. 👍 cc. @Sangminnn 

```tsx
import { hasProperty } from '../../validator';

export const deepCopy = <T>(source: T): T => {
  const weakMap = new WeakMap(); // (*) 이 부분은 더 좋은 네이밍이 있다면 의견주세요!

  // (*) handleDeepCopy 내부 함수 선언(클로저)
  const handleDeepCopy = (source: T) => {
    // Primitive Type
    if (typeof source !== 'object' || source === null) {
      return source;
    }
    
    // deepCopy에 정의한 weakMap을 활용
    // Handling circular references
    if (weakMap.has(source)) {
      return weakMap.get(source);
    }

    // Array
    if (Array.isArray(source)) {
      const newArray: any[] = []; // (*) newArray: any[]

      weakMap.set(source, newArray);
      for (const item of source) {
        newArray.push(handleDeepCopy(item));
      }
      return newArray as T;
    }

    // Set
    if (source instanceof Set) {
      const newSet = new Set(); // (*) newSet: Set<unknown>

      weakMap.set(source, newSet);
      for (const item of source) {
        newSet.add(handleDeepCopy(item));
      }
      return newSet as T;
    }

    // Map
    if (source instanceof Map) {
      const newMap = new Map(); // (*) newMap: Map<any, any>

      weakMap.set(source, newMap);
      for (const [key, value] of source) {
        newMap.set(handleDeepCopy(key), handleDeepCopy(value));
      }
      return newMap as T;
    }

    // Date
    if (source instanceof Date) {
      return new Date(source.getTime()) as T;
    }

    // RegExp
    if (source instanceof RegExp) {
      return new RegExp(source.source, source.flags) as T;
    }

    // Object
    // (*) Record<PropertyKey, any> 타입 지정 
    const newObject: Record<PropertyKey, any> = Object.create(
      Object.getPrototypeOf(source)
    );

    weakMap.set(source, newObject);
    for (const key in source) {
      if (hasProperty(source, key)) {
        // (*)이전에는 Record<string, any>였는데 Object Key에 좀 더 정확한 타입인 PropertyKey로 변경하였습니다.
        newObject[key] = handleDeepCopy(
          (source as Record<PropertyKey, any>)[key]
        );
      }
    }

  return handleDeepCopy(source) as T;
};
```
- 위 코드가 제가 제안하는 전체 코드입니다. 해당 코드도 테스트 코드가 모두 정상적으로 동작합니다.
  - `(*)`변경 사항

<br />

### 1. map 인자
- deepCopy에 `map 인자`가 추가 되는 것은 사용자 입장에서 사용성에 약간 터울(?)이 생길 수도 있다고 생각을 했습니다!
  - 왜냐하면 이 map 인자에 대한 `용도`와 `목적`이 가져다 사용하는 실제 사용자 입장에서 바로 와닿지가 않을 것 같습니다 
  - 예를 들어 `"언제 map이라는 인자를 넘겨야되지? 용도가 뭐지?"`와 같은 생각이 들 것 같습니다. 이 map의 용도(순환 참조 문제 해결)를 이해 하기 위해 실제 구현 코드를 직접 뒤져볼 수 밖에 상황이 발생 할 수도 있을 것 같아요 🥲
  - 물론, `default` 처리를 했기 때문에 옵셔널한 map 인자를 실제로 넘겨주지 않아도 정상 동작하지만 인터페이스 제공(문서 or Typescript 타입 추론) 시 map이 포함되어 있기 때문에 충분히 고려되야하는 사항이라고 생각합니다 🙏
  - (추가로 [lodash cloneDeep](https://lodash.com/docs/4.17.15#cloneDeep)의 경우에도 인자를 하나만 받고 있음)
- **따라서! 실제 copy해주는 `내부 함수(handleDeepCopy, 클로저)`를 선언하고, 상위 스코프(deepCopy)에서 `weakMap`을 생성 후 이를 활용하는 방법은 어떨까요?**
  - 💡 **즉, map을 인자로 받는 것이 아닌 deepCopy내부로 숨기고, 이를 활용하는 아이디어입니다!**
  - 이렇게되면 사용자는 map의 존재를 알 필요도 없고, deepCopy는 내부적으로 기존 `순환 참조` 문제를 해결 할 수 있습니다.
  - 그리고 무엇보다 `이전 버전의 deepCopy와 인터페이스도 동일하게 유지(breaking changing 최소화)`할 수 있습니다! 🎉

<br />

### 2. clone 변수
- 다음은 `clone` 변수인데요! 기존처럼 새로운 값을 반환하는 변수들을 각 블록 스코프에 선언하는 것이 어떨까요? 각 블록으로 선언한다면 네이밍도 기존과 유지해서 `각 블록의 관심사`에 맞게 명확한 네이밍을 제공하면 좋을 것 같습니다 👍
  - 추가로, 각 블록 내에서 관리한다면 타입도 `any보다 조금 더 명확한 타입으로 좁혀서 활용` 할 수 있습니다.
- 아니면 혹시 외부에 clone을 선언한 의도가 따로 있을까요? 🤔 제가 놓친 부분이 있다면 알려주세요!

<br />

### 3. Date, Regex, Object.create(Object.getPrototypeOf(source)) 👍
- 기존 deepCopy의 경우 `Date`와 `Regex`에 대한 처리를 해주고 있지 않았는데요! lodash의 `cloneDeep`도 `Date`와 `Regex`에 대한 처리를 모두 처리해주고 있기때문에 해당 작업들을 추가하는 부분에 대해서 너무 좋은 것 같습니다!!
- 마찬가지로 `Object.create(Object.getPrototypeOf(source))`을 통해 프로토타입을 복사하는 부분도 너무 좋은 것 같습니다! 감사합니다 👍


<br />

### 4. Testing 👍
- 조금 더 명확한 네이밍으로 변경과 `Date`, `Regex`, `순환 참조` 테스트 코드를 추가해주셔서 감사드립니다

2024-05-22 08:43 UTC, Sangminnn commented
@ssi02014 각 케이스에 대해서 명확하게 나누어 처리해주신 것이 너무 좋아보입니다! 👍👍👍

한가지 RegExp의 경우 Prototype에 있는 source를 사용해야하기때문에 불가피하게 source.source에 접근하는 형태가 조금 어색해보이기도 하는데요! 인자로 받는 source의 네이밍을 다른 값으로 바꾸는건 어떨까요 ?? 😄  (ex. value ..?)

로직의 동작에 대해서는 너무 좋아보입니다 👍 

```typescript
 // RegExp as-is
 if (source instanceof RegExp) {
    return new RegExp(source.source, source.flags) as T;
 }

// RegExp to-be
if (value instanceof RegExp) {
    return new RegExp(value.source, value.flags) as T;
}
```

2024-05-22 08:55 UTC, ssi02014 commented
> @ssi02014 각 케이스에 대해서 명확하게 나누어 처리해주신 것이 너무 좋아보입니다! 👍👍👍
> 
> 한가지 RegExp의 경우 Prototype에 있는 source를 사용해야하기때문에 불가피하게 source.source에 접근하는 형태가 조금 어색해보이기도 하는데요! 인자로 받는 source의 네이밍을 다른 값으로 바꾸는건 어떨까요 ?? 😄 (ex. value ..?)
> 
> 로직의 동작에 대해서는 너무 좋아보입니다 👍
> 
> ```ts
>  // RegExp as-is
>  if (source instanceof RegExp) {
>     return new RegExp(source.source, source.flags) as T;
>  }
> 
> // RegExp to-be
> if (value instanceof RegExp) {
>     return new RegExp(value.source, value.flags) as T;
> }
> ```

오우 이 부분은 저도 놓쳤던 부분이네요! 기존 source 인자를 value와 같이 변경하는건 저도 좋은 것 같습니다 🤗
단, 이렇게 될 경우 문서의 수정도 함께 필요해보이네요

2024-05-22 10:48 UTC, hoonloper commented
@ssi02014 
수정된 코드 깔끔하면서 디테일한 부분을 잘 살려주셨다고 생각해요👍
특히, 이제는 잊혀져가는 문법 스킬중 하나인 클로저를 활용한 방법이 인상깊습니다. 

처음 작업할 때 파라미터로 받는 Map을 감추고자 고민했었는데요. (피곤 + 잊혀져가는 JS 문법 이슈)
이유는 많겠지만 가장 우려했던 부분이 호출부에서의 사용 혼동입니다. 임시 변수로 활용하는 자료구조다보니 노출되는 것은 좋지 못한 패턴이라고 생각했거든요.
잘 해결해 주셔서 감사합니다👍

### 1. map 인자
> deepCopy에 map 인자가 추가 되는 것은 사용자 입장에서 사용성에 약간 터울(?)이 생길 수도 있다고 생각을 했습니다!

동의합니다~

> 따라서! 실제 copy해주는 내부 함수(handleDeepCopy, 클로저)를 선언하고, 상위 스코프(deepCopy)에서 weakMap을 생성 후 이를 활용하는 방법은 어떨까요?

좋습니다!

### 2. clone 변수
> 다음은 clone 변수인데요! 기존처럼 새로운 값을 반환하는 변수들을 각 블록 스코프에 선언하는 것이 어떨까요? 각 블록으로 선언한다면 네이밍도 기존과 유지해서 각 블록의 관심사에 맞게 명확한 네이밍을 제공하면 좋을 것 같습니다 👍

좋습니다!

> 아니면 혹시 외부에 clone을 선언한 의도가 따로 있을까요? 🤔 제가 놓친 부분이 있다면 알려주세요!

함수 블록 스코프에서 임시로 사용하는 변수라서 큰 생각없이 let으로 사용했습니다.
kotlin, java로 개발할 때 선언 후 분기문을 지나 할당해주는 경우가 종종 있다보니 무의식 코딩이었던 것 같습니다. 큰 의미는 없어요~


### (*) 변경 사항에 대한 의견

`const weakMap = new WeakMap(); // (*) 이 부분은 더 좋은 네이밍이 있다면 의견주세요!`
영어 실력 이슈로 마땅한 게 떠오르진 않지만 `const storage = new WeakMap();` 정도는 어떠신가요?

이 외 변경 사항 모두 동의합니다!

2024-05-22 11:04 UTC, hoonloper commented
변수명 관련해서 티키타카를 통해 소통이 길어지기보다 임의로 수정 후 최종 리뷰를 통해 결정된 변수명으로 결정지어보려 합니다.

### 수정된 변수명
- deepCopy 인자 `source` -> `value`
- `handleDeepCopy` -> `deepClone`
- `weakMap` -> `referenceMap`
- handleDeepCopy 인자 `source` -> `target`

더 적합한 이름 있으면 반영하겠습니다~

2024-05-22 11:06 UTC, ssi02014 commented
@hoonloper 의견에 공감해주셔서 감사드립니다! 또한 작업해주시느라 고생하셨습니다 👍👍

현재 외부라 귀가 후 수정해주신 코드 다시 한번 확인해보고 코멘트 남기도록 하겠습니다🙇‍♂️

2024-05-22 12:36 UTC, ssi02014 approved these changes
LGTM 🚀

2024-05-22 12:38 UTC, merged

2024-05-22 12:40 UTC, Sangminnn commented
두분 다 너무 고생 많으셨습니다! 👍