feat(react): useHover 훅 추가 완료
modern-agile-team/modern-kit pull request #167
Opened 2024-05-25 05:30 UTC by Sangminnn

## Overview

이전에 이야기나눈 useHover hook을 구현해보았습니다.
참고자료로 주신 use-hooks의 코드도 참고하였고, alibaba의 hooks 레포에 존재하는 useHover hook도 참고하였습니다.
다만 테스트코드를 작성하였으나 계속해서 실패가 나타나 잘못 구현한 부분이 있을지 의견을 여쭤보고자 먼저 풀리퀘 올려드립니다 🙇 

https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useHover/index.ts

## PR Checklist
- [O] All tests pass.
- [O] All type checks pass.
- [O] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-05-25 05:34 UTC, Sangminnn commented
제가 작성했던 테스트코드는 아래와 같습니다.


```typescript
import { describe, it } from 'vitest';
import { screen, renderHook } from '@testing-library/react';
import { renderSetup } from '../../utils/test/renderSetup';
import { useHover } from '.';

describe('useHover', () => {
  it('should trigger callback at target hover and leave', async () => {
    let counter = 0;

    const { result } = renderHook(() =>
      useHover({
        onEnter: () => counter++,
        onLeave: () => counter--,
      }),
    );

    const { user } = renderSetup(<div ref={result.current.ref}>Hover</div>);
    expect(result.current.isHovered).toBe(false);

    const hoverButton = screen.getByText('Hover');

    await user.hover(hoverButton);

    expect(result.current.isHovered).toBe(true); // false로 에러 발생
    expect(counter).toBe(1);
  });
});

```

2024-05-25 05:44 UTC, ssi02014 commented
@Sangminnn 작업감사드립니다!🙇‍♂️🙇‍♂️
제가 이번 주말에는 일정때문에 확인이 힘들어서 다음주중에 확인해보겠습니다

2024-05-25 05:46 UTC, Sangminnn commented
@ssi02014 헉 당연히 괜찮습니다! 주말 편히 잘 보내시고 나중에 시간 괜찮으실때 천천히 확인해주시면 감사드리겠습니다! 🙇👍

2024-05-26 14:36 UTC, ssi02014 requested changes
@Sangminnn useHover 작업 정말 감사드립니다! 리뷰가 정말 늦었네요! 죄송합니다!
몇 가지 의견 드려봅니다!

1. useHover 제네릭 타입 기본 타입(HTMLDivElement)을 안넘겨주는게 좋을 것 같은데 어떻게 생각하실까요!? 왜냐하면 `div` 요소로 해당 훅을 많이 사용할 것 같으면 이런 기본 타입을 지정해줘도 좋을 것 같은데 useHover와 같은 훅은 정말 다양한 요소에서 활용할 수 있을 것 같다고 생각해서 기본 타입은 그냥 안넘겨줘도 되지 않을까 생각해봤네요..!! 🤔

3. `onMouseEnter`, `onMouseLeave` 를 useCallback이 아닌 usePreservedCallback으로 활용해 참조를 유지하면 좋을 것 같습니다 🤗 useEffect에서 onMouseEnter, onMouseLeave를 참조하고 있기 때문에 만약 실제 호출부에서 참조형 상태를 봐꾸게 된다면 무한 호출 이슈가 발생 할 수 있습니다.
    - 이 문제는 useCallback이여도 무한 호출 이슈가 있습니다. (useCallback에서도 onEnter, onLeave를 참조하기 때문)
    - 따라서, useRef로 참조를 유지해주는 `usePreservedCallback`이 훅의 콜백함수에 매핑해주는게 좋습니다. 이건 사실 대부분의 함수를 인자로 받는 모든 커스텀 훅에 필요한 작업입니다.
```tsx
const [state, setState] = useState({ value: 1 });
const { ref } = useHover({
  onEnter: () => {
    setState({ value: 2 });
  }
})
```

5. onEnter, onLeave에 기본 함수로 noop을 넘겨주면 `?.`와 같은 부분이 제거될 수 있을 것 같습니다 🤗
```ts
export const useHover = <T extends HTMLElement>({
  onEnter = noop,
  onLeave = noop,
}: UseHoverProps) => {}
```
아래가 최종 제안 코드입니다.

```tsx
import { noop } from '@modern-kit/utils';
import { usePreservedCallback } from '../../hooks';
import { useEffect, useRef, useState } from 'react';

interface UseHoverProps {
  onEnter?: (event: MouseEvent) => void; // (*) 이벤트 객체는 항상 넘겨주므로 옵셔널로 지정안해도 될 것 같습니다!!
  onLeave?: (event: MouseEvent) => void;
}

export const useHover = <T extends HTMLElement>({
  onEnter = noop, // (*) noop을 기본 함수 지정
  onLeave = noop,
}: UseHoverProps) => {
  const [isHovered, setIsHovered] = useState(false);

  const targetRef = useRef<T>(null);
  
  // usePreservedCallback으로 참조 유지하면서 최신 보장
  const onMouseEnter = usePreservedCallback((event: MouseEvent) => {
    setIsHovered(true);
    onEnter(event);
  });

  const onMouseLeave = usePreservedCallback((event: MouseEvent) => {
    setIsHovered(false);
    onLeave(event);
  });

  useEffect(() => {
    const target = targetRef.current;
    if (!target) return;

    target.addEventListener('mouseenter', onMouseEnter);
    target.addEventListener('mouseleave', onMouseLeave);

    return () => {
      target.removeEventListener('mouseenter', onMouseEnter);
      target.removeEventListener('mouseleave', onMouseLeave);
    };
  }, [onMouseEnter, onMouseLeave]);

  return { ref: targetRef, isHovered };
};
```

2024-05-26 14:48 UTC, ssi02014 commented
@Sangminnn 테스트 코드는 저도 고민해보고 말씀드리겠습니다!!

2024-05-26 14:55 UTC, Sangminnn commented
@ssi02014 봐주시는 것만으로도 감사하기에 전혀 죄송해하지 않으셔도 됩니다! 😄 

1. 안그래도 DivElement를 기본 타입으로 제공하는 방향으로 작업을 하면서도 확신이 들지 않았었는데요! 말씀주신것처럼 해당 타입은 제거하는게 더 좋아보이네요! 👍 
2. 이에 대해서는 이전에도 말씀해주셔서 기억하고있었는데, 제가 제대로 이해하고 있지 못해서 적용하지 않아도 괜찮다고 생각했었네요! 😂  (실제로 첨부해주신것과 똑같이 작성했다가 이해도가 부족해서 지워버렸었던 ...) 지금은 제대로 이해해서 해당 방향으로 수정해서 올려두겠습니다!

감사합니다! 👍👍👍

2024-05-26 15:08 UTC, ssi02014 commented
@Sangminnn renderHook과 renderSetup으로 컴포넌트를 렌더링 하는 부분을 함께 사용하는게 서로 다른 컨텍스트를 가져서 그런 것 같습니다..!! 따라서 renderHook과 renderSetup 중 하나만을 사용해야 될 것 같습니다!

해당 테스트 코드는 hover 이벤트를 발생시켜야 정상적으로 테스트가 가능하기 때문에 `renderSetup`로 테스트를 진행하면 될 것 같습니다!

```tsx
import { screen } from '@testing-library/react';
import { renderSetup } from '../../utils/test/renderSetup';
import { useHover } from '.';
import { Mock } from 'vitest';

describe('useHover', () => {
  const TestComponent = ({
    enterMockFn,
    leaveMockFn,
  }: {
    enterMockFn?: Mock<any, any>;
    leaveMockFn?: Mock<any, any>;
  }) => {
    const { ref, isHovered } = useHover<HTMLDivElement>({
      onEnter: enterMockFn,
      onLeave: leaveMockFn,
    });

    return (
      <div>
        <div ref={ref} role="hover-box">
          Hover Box
        </div>
        {isHovered && <div role="is-hovered-text">hovered</div>}
      </div>
    );
  };

  it('should trigger callback at target hover and leave.', async () => {
    const enterMockFn = vi.fn();
    const leaveMockFn = vi.fn();

    const { user } = renderSetup(
      <TestComponent enterMockFn={enterMockFn} leaveMockFn={leaveMockFn} />
    );

    const hoverBox = screen.getByRole('hover-box');

    await user.hover(hoverBox);

    expect(enterMockFn).toBeCalled();

    await user.unhover(hoverBox);

    expect(leaveMockFn).toBeCalled();
  });

  it('should return the value of isHover based on whether the element is hovered.', async () => {
    const { user } = renderSetup(<TestComponent />);

    const hoverBox = screen.getByRole('hover-box');

    expect(screen.queryByRole('is-hovered-text')).not.toBeInTheDocument();

    await user.hover(hoverBox);

    expect(screen.queryByRole('is-hovered-text')).toBeInTheDocument();

    await user.unhover(hoverBox);

    expect(screen.queryByRole('is-hovered-text')).not.toBeInTheDocument();
  });
});
```

2024-05-26 15:18 UTC, ssi02014 commented
@Sangminnn https://github.com/testing-library/react-testing-library/blob/main/src/pure.js#L274
해당 코드를 보면 renderHook을 사용하면 얘네들이 내부적으로 TestComponent를 생성하고 여기다 이를 적용하는 것 같습니다.
따라서, 저희가 의도한대로 동작을 하지 않을 것 같다는 생각이드네요! 정확한 내용은 아니고.. 뇌피셜입니다

2024-05-26 15:37 UTC, Sangminnn commented
@ssi02014 앗 그런 이슈가 있을 수 있겠군요 ..! 충분히 가능할 것 같다는 생각입니다!
추가로 참고했던 alibaba의 hooks에서의 테스트코드는 저희와 다르게 ref를 hook에서 주입받는 방식이라 render한 screen으로부터 직접 맥락을 받아와 사용해서 문제가 없었을 수 있겠네요 👍 

좋은 의견 감사합니다! 👍 해당 부분은 의견 주신 방향으로 수정해두겠습니다! 🙇 

https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useHover/__tests__/index.test.tsx

2024-05-26 15:40 UTC, ssi02014 commented
@Sangminnn 아휴 아닙니다 제가 더 감사드립니다 🙇‍♂️ 좋은 의견이 더 있으면 말씀주시면 감사드립니다!
저도 또 갑자기 꿈속에서라도 의견이 생긴다면 남겨드리도록 하겠습니다

2024-05-27 00:47 UTC, Sangminnn commented
@ssi02014  의견주신 부분을 반영하였습니다!

1. useHover 내 onEnter, onLeave의 default로 noop 추가
2. onMouseEnter 및 onMouseLeave에 usePreservedCallback 적용
3. 테스트코드를 컴포넌트를 미리 만들어 이 안에서 해당 hook을 연동시키고, 이 컴포넌트를 렌더하여 테스트하는 방식으로 변경

위의 3번을 수행하는 과정에서 role을 부여하여 getByRole을 활용해준 방식에 살짝 의견을 더해 조금 더 의미있는 이름으로 변경해두었습니다.

```typescript
 <div>
  <div ref={ref} role="hover-target">
    Hover me
  </div>
  {isHovered && <div role="conditional-render-text">hovered</div>}
</div>


// ex

await user.hover(hoverTarget);

// 조건부로 렌더되는 텍스트가 없음을 보다 직관적으로 표현하고자 했습니다.
expect(screen.queryByRole('conditional-render-text')).toBeInTheDocument(); 

```

2024-05-27 01:39 UTC, ssi02014 commented on docs/docs/react/hooks/useHover.mdx
> +}
```suggestion
const useIsMounted: <T extends HTMLElement>({
  onEnter?: (event: MouseEvent) => void,
  onLeave?: (event: MouseEvent) => void,
}) => {
  ref: T,
  isHovered: boolean
}
```
작업하시느라 고생하셨습니다!! 문서 인터페이스만 변경되면 될 것 같습니다 👍

2024-05-27 01:42 UTC, Sangminnn commented on docs/docs/react/hooks/useHover.mdx
> +}
@ssi02014 문서 내 템플릿을 가지오는 과정에서 이름을 그대로 뒀군요 😂  확인 감사합니다! 👍

2024-05-27 01:43 UTC, ssi02014 approved these changes

2024-05-27 01:48 UTC, merged

2024-05-27 01:54 UTC, ssi02014 commented
@Sangminnn https://github.com/modern-agile-team/modern-kit/commit/18d29d9b2e08fba1c64b3c8f34506f49b27ef35e
문서 예제를 조금 사용성있게 개선하였습니다 :)