feat(utils): excludeElements
modern-agile-team/modern-kit pull request #182
Opened 2024-05-29 16:14 UTC by Collection50

## Overview

Issue: #160 를 구현했습니다.

### 고민점

- 가장 많이 고민했던 점은 `어느 부분까지 동일하다고 생각할 것인가?` 입니다.
- 튜플, 배열, 객체 등 어떤 자료형까지 exclude 할 수 있을지 고민했습니다.
- #160 에서 말씀해주셨듯 [without](https://lodash.com/docs/4.17.15#without)은 `원시형`만 필터링할 수 있음에 아쉬움이 들었기 때문입니다.

<br/>

### 해결책 `JSON.stringify`

- 초기 [`deepEqual`](https://github.com/modern-agile-team/modern-kit/blob/main/packages/utils/src/common/deepEqual/index.ts)을 사용할까 고민했으나 시간복잡도로 인해 선택하지 않았습니다.
- `object` 타입(array, object 등)인 경우`JSON.stringify`를 통해 동등성을 비교하고자 했습니다.

<br/>

### 대안

- 원시값만 비교하는 코드도 이미 작성해두었습니다.
- @ssi02014 님이 의견 주시면 그에 따라 수정하고자 합니다.
- 시간 복잡도를 개선하고자 `filter` 대신 `Set`을 사용했습니다.

```tsx
export function excludeElements<E>(array: E[], ...args: E[]) {
  const excludeSet = new Set(args);

  return array.filter((element) => !excludeSet.has(element));
}
```

close #160 

<br/>

## PR Checklist
- [x] All tests pass.
- [x] All type checks pass.
- [x] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-05-29 18:53 UTC, ssi02014 commented on packages/utils/src/array/excludeElements/index.ts
> +}
@Collection50 작업하시느라 정말 고생하셨습니다!

의도를 말씀해주신대로 원시값 뿐만아니라 `배열`, `객체` 등 비교해서 `exclude`해주는 방향은 저도 좋은 것 같습니다! 
이때 비교를 deepEqual보다 `JSON.stringify`로 비교하는 부분도 좋은 것 같습니다!
간단하게 테스트해봤을 때 deepEqual이 성능적으로 더 안좋은 것으로 확인했습니다. 전반적으로 좋은 작업이라 생각합니다!

단, 타입 부분 개선이 필요할 것 같은데요!

현재 코드에서는 우선 Readonly 배열 타입의 인자 할당이 불가능합니다.
```ts
const test1 = [1, 2, "123", 3, 4] as const; // readonly [1, 2, "123", 3, 4]
const excludeArr1 = [3, 2] as const; // readonly [3, 2]

const ex1 = excludeElements(test1, ...excludeArr1); // typeError
// 'readonly [1, 2, "123", 3, 4]' 형식의 인수는 '(2 | 3)[]' 형식의 매개 변수에 할당될 수 없습니다.
```

그래서 첫 번째 개선 사항으로 아래와 같이 `Readonly 배열`도 할당 할 수 있게끔 수정하였습니다.

```tsx
export const excludeElements<E> = (
  array: ReadonlyArray<E> | E[],
  ...args: ReadonlyArray<E> | E[]
) => {
  const excludeSet = new Set(args.map((arg) => JSON.stringify(arg)));

  return array.filter((element) => !excludeSet.has(JSON.stringify(element)));
}
```

하지만 해당 개선 사항의 경우 array와 args의 타입을 동일하게 가져가기 때문에 둘의 타입이 다르다면 타입 에러가 발생합니다.
대충 array가 `number[]` 으로 넓은 타입이라면 크게 문제는 없지만 `as const`를 활용해 타입을 좁혀서 활용하는 경우에는 문제가 발생합니다.

```ts
const test1 = [1, 2, "123", 3, 4] as const; // readonly [1, 2, "123", 3, 4]
const excludeArr1 = [3, 2]; // number[]

const ex1 = excludeElements(test1, ...excludeArr1); // TypeError
// 'number[]' 형식의 인수는 'readonly (1 | 2 | "123" | 3 | 4)[] | (1 | 2 | "123" | 3 | 4)[]' 형식의 매개 변수에 할당될 수 없습니다.
```

그래서 두 번째 개선사항으로 `array`, `args`의 두 개의 인자를 각각 제네릭을 받는 형태로 수정하였습니다.
 
```ts
export const excludeElements = <T, U>(
  array: ReadonlyArray<T> | T[],
  ...args: ReadonlyArray<U> | U[]
): T[] => {
  const excludeSet = new Set(args.map((arg) => JSON.stringify(arg)));

  return array.filter(
    (element) => !excludeSet.has(JSON.stringify(element))
  ) as T[];
};
```

위와 같이 수정 후에는 기존에 제안 드렸던 타입 에러가 발생하지 않습니다.

```tsx
const test1 = [1, 2, "123", 3, 4] as const; // readonly [1, 2, "123", 3, 4]
const excludeArr1 = [3, 2] as const; // readonly [3, 2]

const test2 = [1, 2, "123", 3, 4]; // (string | number)[]
const excludeArr2 = [3, 2]; // number[]

const ex1 = excludeElements(test1, 3, 2); // (1 | 2 | "123" | 3 | 4)[]
const ex2 = excludeElements(test1, ...excludeArr1); // (1 | 2 | "123" | 3 | 4)[]
const ex3 = excludeElements(test2, ...excludeArr2); // (string | number)[]
```

<br />

여기서 추가로 시도했던 부분은 반환 타입으로 `Exclude` 유틸 타입을 활용하는 것이였습니다.
예를 들어 기대했던 동작은 아래와 같습니다.

```ts
excludeElements([1, 2, 3] as const, ...[1, 2] as const); // 3[]
```
하지만, `as const`를 활용해 타입을 최대한 좁혀서 사용한 경우에는 적절하게 동작을 했는데, 더 넓은 타입 혹은 다양한 타입의 요소를 포함한 배열의 경우 타입 추론이 원활하게 되지 않았네요. 

`extends`와 같은 조건부 타입을 활용해봐도 좋은 방법을 찾지 못했네요 🥲

```ts
const ex7 = excludeElements1([1, 2, 3], ...[1, 2]); // never[]
const ex8 = excludeElements1([1, 2, 3, "123"], ...[1, 2]); // string[]
```

그래서 반환 타입은 그냥 첫 번째 인자인 `array의 타입을 반환을 하는 방향`으로 고민을 하게 되었습니다!
만약, 다양한 상황에서 반환 타입을 명확하게 추론할 수 있게끔 한다면 이게 가장 좋을 것 같지만 이 부분에 대한 고민이 많이 필요한 상황입니다.

혹시라도 좋은 의견 있을까요? 🙏 너무 복잡하다면 반환 타입은 array 타입을 가져가는 방향으로 진행해도 좋을 것 같습니다 🤗

2024-05-29 18:58 UTC, ssi02014 commented on packages/utils/src/array/excludeElements/index.ts
> +}
추가적으로 다른 모듈들과의 컨벤션을 위해 함수 선언문이 아닌 화살표 함수로 변경해주시면 감사드립니다! 🙇‍♂️

2024-05-29 18:59 UTC, ssi02014 requested changes
고생하셨습니다! 전반적인 작업은 좋다고 느꼈습니다! 타입에 대한 문제만 개인적으로 고민해보고 의견을 남겨봤습니다! 한번 검토해주시면 감사드립니다 :)

2024-05-30 04:23 UTC, Collection50 commented on packages/utils/src/array/excludeElements/index.ts
> +}
항상 정성스럽게 리뷰 해주셔서 감사드립니다 👍 
입력값과 출력값 형식에 대해서도 조금 더 고민하는 습관을 들이겠습니다 ☺️

> Readonly 배열도 할당 할 수 있게끔 수정하였습니다.
- `Readonly` 타입을 추가하겠습니다.

<br/>

> 반환 타입으로 `Exclude` 유틸 타입을 활용하는 것
- 이 부분을 확인하여 아래와 같은 코드를 작성했지만, 말씀하신대로 명확한 추론은 어려웠습니다.

```tsx
export const excludeElements = <E, U extends E>(
  array: ReadonlyArray<E> | Array<E>,
  ...args: ReadonlyArray<U> | Array<U>
): Exclude<E, U>[] => {
  const excludeSet = new Set(args.map((arg) => JSON.stringify(arg)));

  return array.filter(
    (element) => !excludeSet.has(JSON.stringify(element))
  ) as Exclude<E, U>[];
};
```


<br/>

### 1개의 제네릭을 사용했던 이유

- 아래의 이유로 `여러개의 자료형이 섞인 경우, excludeElements의 의미가 적다.`고 생각했습니다.

<br/>

1. 자바스크립트가 아닌 `Typescript` 라이브러리인 점
2. 배열은 **동일한 요소의 나열**로의 의미가 강해 실무에서도 뒤섞여진 배열을 잘 사용하지 않는다는 점(배열의 타입 할당 어려움)
    - (이 부분에 대한 냉정한 피드백 부탁드립니다.)

타입을 1개로 제한하여 사용자가 다른 타입을 `exclude` 하려는 경우 컴파일 오류로 DX를 향상하고자 했습니다.

<br/>

하지만 컨트리뷰터로서 메인테이너 분들의 의견을 적극적으로 수용하고 싶습니다. 😀
원하는 방향성에 대해 편하게 말씀해주시면 감사하겠습니다 ! 🙏

2024-05-30 05:44 UTC, ssi02014 commented on packages/utils/src/array/excludeElements/index.ts
> +}
@Collection50 좋은 의견 감사합니다!

> 배열은 동일한 요소의 나열로의 의미가 강해 실무에서도 뒤섞여진 배열을 잘 사용하지 않는다는 점

실제 개발 할 때 뒤죽박죽 타입의 배열을 자주 사용하는 케이스가 적다는 것은 동의합니다! 👍
  - 하지만 이를 완전히 배제할 수는 없습니다. 누군가는 완전히 뒤죽박죽은 아니겠지만 `(string | number)[]`와 같은 배열 정도는 사용 할 수 있습니다.

위 댓글에서 제안 주신 코드(제네릭 타입1개, 제네릭 타입 2개)와 기존 제네릭이 하나만 있을 때 코드를 비교 했을 때 몇 가지 테스트를 해봤는데요! 
  - excludeElements 가 제네릭 타입1개
 
```ts
export const excludeElements = <E>(
  array: ReadonlyArray<E> | Array<E>,
  ...args: ReadonlyArray<E> | Array<E>
): Array<E> => {
  const excludeSet = new Set(args.map((arg) => JSON.stringify(arg)));

  return array.filter(
    (element) => !excludeSet.has(JSON.stringify(element))
  ) as Array<E>;
};
```
  - excludeElements2 가 제네릭 타입2개

```ts
export const excludeElements2 = <E, U extends E>(
  array: ReadonlyArray<E> | Array<E>,
  ...args: ReadonlyArray<U> | Array<U>
): Array<E> => {
  const excludeSet = new Set(args.map((arg) => JSON.stringify(arg)));

  return array.filter(
    (element) => !excludeSet.has(JSON.stringify(element))
  ) as Array<E>;
};
```
  
```ts
// Case1. exclude 배열에 test에 없는 타입의 배열 요소 존재
const test = [1, 2, 3, "123"];
const exclude = [2, 3, true];

excludeElements(test, ...exclude); // 타입 에러
// '(number | boolean)[]' 형식의 인수는 '(string | number)[] | readonly (string | number)[]' 형식의 매개 변수에 할당될 수 없습니다.
excludeElements2(test, ...exclude); // 타입 에러
// '(number | boolean)[]' 형식의 인수는 '(string | number)[] | readonly (string | number)[]' 형식의 매개 변수에 할당될 수 없습니다.

// Case2. exclude에 test1에 존재하지 않은 요소 존재
const test1 = [1, 2, 3] as const;
const exclude1 = [2, 3, 4] as const;

excludeElements(test1, ...exclude1); // 타입 통과
excludeElements2(test1, ...exclude1); // 타입 에러
// '[2, 3, 4]' 형식의 인수는 'readonly (1 | 2 | 3)[] | (1 | 2 | 3)[]' 형식의 매개 변수에 할당될 수 없습니다.

// Case3. exclude가 더 넓은 타입(다운 캐스팅)
const test2 = [1, 2, 3] as const;
const exclude2 = [2, 3];

excludeElements(test2, ...exclude2); // 타입 통과
excludeElements2(test2, ...exclude2); // 타입 에러
// 타입스크립트는 다운 캐스팅을 대부분 허용하지 않습니다.
// 'number[]' 형식의 인수는 'readonly (1 | 2 | 3)[] | (1 | 2 | 3)[]' 형식의 매개 변수에 할당될 수 없습니다.

// Case4. exclude가 더 좁은 타입(업 캐스팅)
const test3 = [1, 2, 3];
const exclude3 = [2, 3] as const;

excludeElements(test3, ...exclude3); // 타입 통과
excludeElements2(test3, ...exclude3); // 타입 통과

// Case5. exclude배열이 test 배열의 서브 타입
const test4 = [1, 2, 3] as const;
const exclude4 = [2, 3] as const;

excludeElements(test4, ...exclude4); // 타입 통과
excludeElements2(test4, ...exclude4); // 타입 통과

// Case6. 같은 number[] 배열
const test5 = [1, 2, 3];
const exclude5 = [2, 3];

excludeElements(test5, ...exclude5); // 타입 통과
excludeElements2(test5, ...exclude5); // 타입 통과
```

저는 제안 주신 코드에서 제네릭 2개가 더욱 명확하게 타입 체크를 해준다고 느꼈네요!

> 사용자가 다른 타입을 exclude 하려는 경우 컴파일 오류로 DX를 향상하고자 했습니다.

위에서 말씀주신 DX 관점에서 명확하게 타입에러를 잡아주기 때문에 이게 더 나은 방향이 아닐까 고민을 했습니다 🤔
이러한 결과에 대해서는 어떻게 생각 하시는지 의견이 궁금합니다!

추가로 혹시 제가 놓치고 있는 부분이 있으면 언제든 말씀해주세요!! 다시 한번 감사드립니다 🤗

2024-05-30 06:10 UTC, Collection50 commented on packages/utils/src/array/excludeElements/index.ts
> +}
하나라도 타입의 컴파일 오류를 캐치할 수 있는 것이 좋은 방향이라고 생각합니다 ! 
추후 기여에는 여러가지의 타입 테스트를 보완하겠습니다 ! 🙌

다운 캐스팅과 업캐스팅에 대한 예시도 상세하게 작성해주셔서 이해하기 정말 편했습니다 !
제가 더욱 감사드립니다 😀
훌륭한 라이브러리에 기여할 수 있다는 점이 감사합니다 ! ✨

2024-05-30 06:48 UTC, ssi02014 approved these changes
LGTM! 🎉 작업하시느라 고생하셨습니다!
추후에 개선점을 발견하신다면 또 의견주시면 감사드릴게요! cc. @Sangminnn

2024-05-30 06:55 UTC, Sangminnn commented
저도 이야기 나누신 부분 잘 확인했습니다! 더 좋은 방법이 있을지는 별도로 고민해보겠습니다 😄 
두분 다 너무 고생 많으셨습니다! 🙇

2024-05-30 06:55 UTC, Sangminnn approved these changes

2024-05-30 07:15 UTC, merged

2024-05-30 07:52 UTC, ssi02014 commented
@Collection50 반영하기 전에 미처 changsetlog를 추가하지 못해 https://github.com/modern-agile-team/modern-kit/commit/6a51b64c23d647cc1c8f6db391dcfcbd07ce4d1d 해당 커밋에서 추가하였습니다 다시 한번 작업하시느라 고생하셨고, 감사드립니다

2024-05-30 10:33 UTC, Collection50 commented
> @Collection50 반영하기 전에 미처 changsetlog를 추가하지 못해 [6a51b64](https://github.com/modern-agile-team/modern-kit/commit/6a51b64c23d647cc1c8f6db391dcfcbd07ce4d1d) 해당 커밋에서 추가하였습니다 다시 한번 작업하시느라 고생하셨고, 감사드립니다

혹시 기여자가 `changesetlog`를 변경해야 하는 걸까요?
제 의무를 다하고 있는지 궁금해서 여쭤봅니다.. !

훌륭한 레포지토리에 기여한 경험이 적어서 지도해주시면 감사하겠습니다.

2024-05-30 10:43 UTC, ssi02014 commented
@Collection50 아닙니다ㅎㅎ changelog는 관리자가 추가하는게 맞는 것 같아요! 제가 놓친 부분입니다 크게 신경쓰지 않으셔도 됩니다 😄