feat(react): useMouse 훅 추가 완료
modern-agile-team/modern-kit pull request #186
Opened 2024-05-31 14:03 UTC by Sangminnn

## Overview

Issue: #153 

특정 엘리먼트를 기준으로 현재 스크린에서의 위치, 스크린 영역 내의 위치, 전체 문서에서의 위치, 대상 엘리먼트 기준 위치를 제공하는 훅입니다.

## PR Checklist
- [O] All tests pass.
- [O] All type checks pass.
- [O] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-05-31 14:04 UTC, Sangminnn commented on packages/react/src/hooks/useMouse/index.ts
> +  const [cursorPosition, setCursorPosition] = useState<CursorPosition>({
initial State의 타입을 number로 가지고가면서도 0을 제공하게된다면 올바르지 않은 정보를 제공할 수 있기때문에 NaN을 제공하는 방법을 사용해보았습니다.

2024-05-31 14:05 UTC, Sangminnn commented on docs/docs/react/hooks/useDocumentTitle.mdx
useDoumentTitle 오탈자를 발견하여 수정해두었습니다.

2024-05-31 14:10 UTC, Sangminnn commented
@ssi02014 테스트코드에 대한 부분은 미흡한 면이 있습니다. 보완할 부분이 있다면 편하게 의견주시면 너무 감사드리겠습니다! 🙇

2024-05-31 15:02 UTC, ssi02014 reviewed
작업하시느라 고생하셨습니다!
테스트 코드 검토 이전에 훅 코드에대해 간단한 의견을 드려봅니다!

2024-05-31 15:02 UTC, ssi02014 commented on packages/react/src/hooks/useMouse/index.ts
> +  }, []);
이벤트 바인딩은 element가 아닌 `doucment`가 되면 좋을 것 같습니다!!
누군가는 `targetRef`를 넘기지 않더라도 `relativeX, Y를 제외한 좌표 값`들을 원하는 니즈가 있을 수 있습니다!

현재는 element를 넘겨주고, 해당 element의 mouse이벤트가 트리거될 때만 이를 계산합니다

https://github.com/uidotdev/usehooks/blob/main/index.js#L809

useHooks의 경우에는 ref가 있을 경우라면 조건식으로 이를 분기처리해서 새로운 상태로 변경합니다

2024-05-31 15:02 UTC, ssi02014 commented on packages/react/src/hooks/useMouse/index.ts
> +  return { targetRef, position: cursorPosition };
```suggestion
  return { ref, position: cursorPosition };
```
다른 ref들과 네이밍 컨벤션을 맞추면 좋을 것 같습니다!

2024-05-31 15:04 UTC, ssi02014 commented on packages/react/src/hooks/useMouse/index.ts
> +  useLayoutEffect(() => {
useLayoutEffect보다 서버사이드 렌더링 환경을 대비하기위해  `useIsomorphicLayoutEffect` 사용하면 어떨까요!?

2024-06-01 07:41 UTC, Sangminnn commented on packages/react/src/hooks/useMouse/index.ts
> +  const [cursorPosition, setCursorPosition] = useState<CursorPosition>({
오호 저도 레퍼런스로 보던 곳(alibaba의 hooks입니다) 에서 NaN으로 초기값을 가지고 처리하는 것을 보고 생각보다 이런 관점도 있겠구나 싶어서 차용을 해보았는데 말씀주신 것처럼 개념 자체를 돌아보니 오히려 일반적인 접근으로 옵셔널로 처리해서 가지고있는 것도 좋겠네요! 

이 부분은 수정해두겠습니다! 감사합니다! 👍

2024-06-01 07:41 UTC, Sangminnn commented on packages/react/src/hooks/useMouse/index.ts
> +  }, []);
이 부분은 고려하지 못했었군요! 너무 좋은 접근방식으로 보여 수정해두겠습니다! 👍

2024-06-01 07:42 UTC, Sangminnn commented on packages/react/src/hooks/useMouse/index.ts
> +  useLayoutEffect(() => {
엇 그렇군요! 이 부분은 제가 놓쳤었네요! 당연히 말씀주신 방법이 더 좋은 방법으로 보여 위에 말씀주신 부분과 같이 수정해두겠습니다! 👍

2024-06-01 08:00 UTC, ssi02014 commented on packages/react/src/hooks/useMouse/index.ts
> +  const [cursorPosition, setCursorPosition] = useState<CursorPosition>({
@Sangminnn 긍정적으로 의견받아주셔서 감사합니다! 🤗

2024-06-01 09:25 UTC, Sangminnn commented
@ssi02014  주신 피드백을 반영해두었습니다!

1. useMouse 훅의 initialState를 undefined로 변경 및 옵셔널 적용 완료
2. document에 event listener를 달아 ref를 사용하지 않는다면 기존값에서 relative 값에는 변화가 없도록 수정 완료
3. return 인터페이스를 ref로 수정
4. useLayoutEffect -> useIsomorphicLayoutEffect 으로 변경 완료
5. 위와 같은 명세를 적용하며 테스트코드를 with ref 와 without ref 케이스로 수정 완료

매번 놓치는 부분도 많은데 꼼꼼하게 봐주시고 좋은 의견 주셔서 항상 감사합니다! 😄 🙇

2024-06-01 09:47 UTC, ssi02014 requested changes
전반적으로 너무 좋은 작업 같습니다! 고민을 해봤는데 몇 가지있어 코멘트로 남겨봅니다!

2024-06-01 09:47 UTC, ssi02014 commented on packages/react/src/hooks/useMouse/index.ts
> +      }
여기서 `relativeX/Y`뿐만아니라 ref로 넘겨주는 요소의 위치 자체도 추가되면 좋을 것 같아요!

```ts
const elementPositionX = rect.left + window.scrollX;
const elementPositionY = rect.top + window.scrollY;
```

ref로 넘겨주는 요소에 대한 위치값이 추가됨에따라 relative에도 약간의 구체적인 네이밍 변화가 있으면 좋을 것 같네요!
`elementRelativeX/Y` 를 생각해봤는데 어떠실까요?!

2024-06-01 09:47 UTC, ssi02014 commented on packages/react/src/hooks/useMouse/useMouse.spec.tsx
> +    }, []);
현재 테스트 코드를 봤을 때 해당 style은 필요 없을 것 같습니다!

2024-06-01 11:40 UTC, Sangminnn commented on packages/react/src/hooks/useMouse/index.ts
> +      }
@ssi02014 처음에는 훅에서 제공하는 역할이 아무래도 Mouse에 대한 정보이다보니 연결된 ref의 포지션을 반환해주는 것이 맞을지 고민하다가 제외했었는데요! 

해당 훅에서 제공해주지 않는다면 해당 훅에서 반환하는 ref와 별도의 ref를 사용자가 useMergeRef를 사용해서해야하는데, 이러한 부분까지 사용자가 고려하는 것은 과거의 대화에서 지양하는 방향으로 갔던 것으로 기억하고 있네요! 

그렇다고한다면 오히려 ref 자체로서의 역할을 본다고 하면 해당 엘리먼트의 위치를 원하는 니즈도 있다면 반환해주는 것이 맞을듯 하네요! 이런 방향이라면 relativeX, relativeY에서 조금 더 구체적으로 제안해주신 변수명도 좋아보입니다! 👍 

이 부분은 재수정해서 올려두겠습니다! 👍

2024-06-01 11:51 UTC, ssi02014 commented on packages/react/src/hooks/useMouse/index.ts
> +      }
@Sangminnn 피드백 정말 감사합니다! 말씀하신 부분도 맞습니다! 초기에 목적은 mouse에 정보를 다루는데 포커스를 둔 게 사실입니다!

약간 조금 더 사용성 고민을 해보면서 `ref를 할당할 수 있는 특징`도 있고, 이런 특정 요소 relative 포지션 정보 + 위치 정보까지만 더 추가를 한다면 훨씬 더 사용성에 좋지 않을까!? 생각을 해봤습니다! (+useMergeRef 부분도 동의합니다!) 

다시 한번 감사드립니다!

2024-06-01 12:27 UTC, Sangminnn commented on packages/react/src/hooks/useMouse/index.ts
> +      }
@ssi02014 아닙니다! 도움은 제가 받았는걸요 😂 
항상 다양한 시선에서 좋은 의견주심에 감사드립니다 🙇 

의견 주신 부분은 훅의 코드와 문서, 테스트코드 전부 수정 및 반영해두었습니다!

2024-06-01 12:43 UTC, ssi02014 approved these changes
작업하시느라 정말 고생하셨씁니다!
으악 changsetlog 오타가 나버렸습니다 ㅠㅠㅠㅠ
changesetlog만 수정해주시고 병합해주셔도 될 것 같습니다! + 문서 ref오타

2024-06-01 12:44 UTC, ssi02014 commented on docs/docs/react/hooks/useMouse.mdx
> +  const { targetRef, position } = useMouse<HTMLDivElement>();
헉 이부분 ref로 수정해주시면 감사드립니다! usage와 example 모두 수정이 필요할 것 같습니다!

2024-06-01 12:49 UTC, ssi02014 commented on .changeset/chilled-icons-sniff.md
> +"@modern-kit/react": minoe
```suggestion
"@modern-kit/react": minor
```

2024-06-01 12:50 UTC, Sangminnn commented
헉 기존 로그를 두고 새로 만들어버렸군요! 다시 수정하겠습니다! 🏃

2024-06-01 12:53 UTC, merged

2024-06-01 12:54 UTC, Sangminnn commented
@ssi02014 마지막까지 꼼꼼하게 봐주셔서 감사합니다! 다음에는 잊지않고 changeset log도 신경쓰겠습니다! 👍