feat(utils): isFloat 함수 추가 완료
modern-agile-team/modern-kit pull request #230
Opened 2024-06-16 09:31 UTC by Sangminnn

## Overview

Issue: #228 

Number의 inInteger는 숫자 중 정수만을 판별해냅니다.

isFloat를 사용하면 숫자 중 실수를 판별해낼 수 있습니다.

## PR Checklist
- [ ] All tests pass.
- [ ] All type checks pass.
- [ ] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-06-16 09:32 UTC, Sangminnn commented on packages/utils/src/number/isFloat/index.ts
> +  if (typeof value !== 'number' || !isFinite(value)) return false;
isFinite함수를 통해 Number타입이지만 NaN, Infinity, -Infinity 와 같은 케이스를 전부 제거합니다.

2024-06-16 15:17 UTC, ssi02014 requested changes
@Sangminnn 작업 정말 감사드립니다! 여러 면에서 테스트해보고 조사한 뒤 리뷰 남깁니다!! 

<br />

`isFloat`이라는게 저는 `부동소수점 실수(float)`임을 판단한다고 이해를 했는데요! 🙏
현재 isFloat함수는 `실수`뿐만아니라 `정수`까지 모든 `유한수`를 포함하는 함수라고 이해됩니다!
  - 사실상, `Number.isFinite`함수와 동일한 동작을 하는 것 같습니다. (테스트 상 동일한 결과를 가져왔습니다)
  - 현재는 `전역 isFinite`를 사용하셨는데, `Number.isFinite`두 함수의 동작에 차이가 있습니다.
  - 추측상 `전역 isFinite`의 자동 형변환 특징 때문에 `typeof value === 'number'`를 사용하셨던 것 같네요!

```ts
Number.isFinite("0"); // false
// 전역함수 isFinite('0')라면 true
Number.isFinite(null); // false
// 전역함수 isFinite(null)라면 true
```
- [Number.isFinite](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite)
- [전역 isFinite](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/isFinite)

<br />

함수의 네이밍대로 유한수 범위가 아닌 `부동소수점(float)실수임을 판단`하는 더 좁은 의미의 함수가 적절할 것 같은데 어떻게 생각 하실까요?

저는 아래와 같은 로직을 생각해봤습니다!
```ts
const isFloat = (value: unknown): value is number => {
  return (
    Number.isFinite(value) && 
    !Number.isInteger(value)
  );
};
```
- `Number.isFinite`로 `유한수`를 판단합니다. 이때, `전역 isFinite`처럼 자동 형변환 후 판단하는게 아니기 때문에 이 시점에서 `null`, `undefined`, `Infinity`등도 모두 검증 할 수 있습니다.
- `!Number.isInterger`로 부동소수점임을 판단합니다.
- 추가로, value를 number로 타입을 좁히기 위해 `value is number`를 추가합니다

### 결과
```ts
isFloat(100); // 정수 false
isFloat(0); // 정수 false
isFloat(0.5); // 부동 소수점 true
isFloat(-0.5); // 부동 소수점 true
isFloat(1.999989899); // 부동 소수점 true
isFloat(-1.50010101011); // 부동 소수점 true
isFloat(1e3); // 정수 1000 소수점 true
isFloat(2.5e-3); // 부동 소수점 true
```
그 외 타입 모두 `false`

```ts
isFloat("");
isFloat(null);
isFloat(undefined);
isFloat(false);
isFloat(NaN);
isFloat(Infinity);
isFloat(-Infinity);
isFloat([]);
isFloat({});
```

<br /> 

### hasDecimal
https://github.com/modern-agile-team/modern-kit/pull/205/files#r1626020397
추가적으로 위 댓글로 의견 남겨주셨던 부동소수점 문제도 고려해봤는데요!
결국 `Number.isInterger`과 결과가 같더라구여!

```ts
// true
console.log(hasDecimal(5.123)); // true
console.log(!Number.isInteger(5.123)); // true

console.log(hasDecimal(5.000000000000001)); // true
console.log(hasDecimal(450000000000000.1)); // true

console.log(!Number.isInteger(5.000000000000001)); // true
console.log(!Number.isInteger(450000000000000.1)); // true

// false
console.log(hasDecimal(5.0000000000000001)); // false
console.log(hasDecimal(5.0000000000000001)); // false

console.log(!Number.isInteger(5.0000000000000001)); // false
console.log(!Number.isInteger(4500000000000000.1)); // false
```

## 결론
```ts
const isFloat = (value: unknown): value is number => {
  return (
    Number.isFinite(value) && 
    !Number.isInteger(value)
  );
};
```
결과적으로 `Number.isInterger`를 활용하면 좋을 것 같습니다 🤗

2024-06-17 05:38 UTC, Sangminnn commented
@ssi02014 와 꼼꼼하게 확인해주시고 자세하게 설명해주셔서 정말 너무 감사드립니다! 🙇 

1. 말씀주신것과 같이 제가 처음 의도한 바는 유한수를 체크하는 것이 의도했던 바가 맞습니다! 이전에 전역 isInteger와 Number.isInteger 의 차이에 대해서 언급해주셨던 것을 기억하고 위의 로직도 동일하게 체크했어야 했는데 제가 놓쳤네요 😭 정확하게 비교해주셔서 감사합니다!

2. 저 역시도 말씀주신 것과 같이 위의 최초 의도였던 **유한수 체크**가 불필요하게 됨에 따라, 이를 **유한수 범위가 아닌 부동소수점(float)실수임을 판단하는 더 좁은 의미의 함수** 로 변경하는 것에 동의합니다! 최초 위의 작업을 할때 저도 실제로

**실수** 라는 것이 **수학적인 측면에서는 유한수**를 의미하기도 하고 **코드의 관점**에서는 **부동소수점을 체크**하는 네이밍을 가지고있다보니 두가지 역할 중 어떤것을 채택할지 고민이었는데요! 첫번째의 이름으로서의 역할이 기존의 메서드로 인해 무의미해졌기에 두번째 이름으로서의 역할로 가는 것이 더 좋아보이고, 실제 코드적인 측면에서도 후자로서의 역할을 하게된다면 최초에 생각했던 방법은

```typescript
const isFloat = (value: unknown): value is number => {
  return (
    Number(value) && Number(value) % 1 !== 0 // 나머지가 0인지를 체크
  );
};
```

위와 같은 방법이었습니다만, 제안해주신 방법이 훨씬 더 선언적으로 느껴져서 해당 코드를 사용하는 방향으로 진행하면 좋을듯합니다!




정리해보자면


1. 기존의 역할은 제거하고 부동소수점을 체크하는 역할의 isFloat로 코드 수정하겠습니다.
2. 부동소수점의 확인은 JS고유의 문제로 이를 해결할 수 있는 방법이 있는지는 코드를 수정하면서 조금 더 찾아보도록 하겠습니다.


다시한번 자세히 확인해주셔서 너무 감사드리고 괜찮으시다면 위의 방향으로 제가 수정해두겠습니다! 🫡 👍

2024-06-17 05:49 UTC, ssi02014 commented
@Sangminnn 넵!! 긍정적으로 봐주셔서 감사합니다! 다시한번 작업해주셔서 감사드립니다 🙇🏻‍♂️

2024-06-17 15:07 UTC, Sangminnn commented
@ssi02014 해당 로직은 제안해주신 방향으로 수정 및 테스트코드, 문서를 수정해두었습니다!

부동소수점 문제는 확실히 인자로 값을 넘기는 순간부터 정수로 변경이 되어버려서 로직으로 풀어가기가 어려워보이네요 🥹

2024-06-17 15:12 UTC, ssi02014 commented on packages/utils/src/number/isFloat/index.ts
> +};
```ts
const isFloat = (value: unknown): value is number => {}
```
타입을 좁히기 위해 `is`가 추가되어야 할 것 같습니다!

2024-06-17 15:17 UTC, Sangminnn commented on packages/utils/src/number/isFloat/index.ts
> +};
엇 해당 함수가 boolean을 반환하게될것같은데 number로의 타입가드가 필요할까요 ?? 👀

2024-06-17 15:23 UTC, ssi02014 commented on packages/utils/src/number/isFloat/index.ts
> +};
value의 타입이 unknown이기 때문에 해당 함수가 true가 된다면 value의 타입을 number로 좁혀주면 좋을 것 같습니다 !

```ts
// as-is
const value = 0 as unknown;

if (isFloat(value)) {
  // value: unknown
} else {
  // value: unknown
}
```

```ts
// to-be
const value = 0 as unknown;

if (isFloat(value)) {
  // value: number
} else {
  // value: unknown
}
```

2024-06-17 15:34 UTC, Sangminnn commented on packages/utils/src/number/isFloat/index.ts
> +};
헉 바보같은 질문이었군요! value가 좁혀지는것인데 반환타입만 생각하고있었네요 😭 
말씀주신 방법이 당연히 더 좋아보입니다! 바로 수정해두겠습니다! 🏃

2024-06-17 15:48 UTC, ssi02014 approved these changes
작업하시느라 너무 고생하셨습니다!
마지막으로 `utils/index.ts`에서 number를 export하면 병합을 진행해도 될 것 같습니다!

```ts
export * from './array';
export * from './clipboard';
export * from './common';
export * from './device';
export * from './formatter';
export * from './number'; // (*)
export * from './file';
export * from './object';
export * from './regex';
export * from './storage';
export * from './string';
export * from './style';
export * from './validator';
```

2024-06-17 15:53 UTC, merged

2024-06-17 15:54 UTC, Sangminnn commented
@ssi02014 잘못된 방향으로 생각하기도 하고 놓친 부분이 많았는데 늦은시간까지 확인해주셔서 너무 감사합니다! 👍 
(github action의 테스트가 끝나면 머지하려고했는데 해주셨군요! 😂 감사합니다! 🙇 )