feat(utils): intersection 함수 작업 완료
modern-agile-team/modern-kit pull request #243
Opened 2024-06-19 13:12 UTC by Sangminnn

## Overview

Issue: #197 

`두 배열 내에서 동일하게 존재하는, 교차된 값에 대한` 새로운 배열을 반환하는 함수입니다.

기본적으로 `원시 값`에 대해서만 중복 요소를 판단하며, 필요 시 3번째 인자인 `comparator` 함수 결과로 교차되는 요소임을 판단할 수 있습니다.

`comparator`의 기본값은 `Object.is` 입니다.

## PR Checklist
- [ ] All tests pass.
- [ ] All type checks pass.
- [ ] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-06-19 13:13 UTC, Sangminnn commented on packages/utils/src/array/intersection/index.ts
> +) => {
arr1에 존재하는 중복을 제거하고 hash table로 접근하기 위해 Set을 활용하였습니다.

2024-06-19 13:14 UTC, Sangminnn commented on packages/utils/src/array/intersection/index.ts
> +
comparator에 대한 검증과 arr2를 순회하며 발생하는 중복값이 존재한다면 이는 재검증하지 않도록 checked라는 Set객체를 활용했습니다.

2024-06-19 15:04 UTC, ssi02014 requested changes
```ts
import { identity } from '../../common';

export const intersection = <T, U = T>(
  arr1: T[] | readonly T[],
  arr2: T[] | readonly T[],
  iteratee: (item: T) => T | U = identity
) => {
  const set = new Set(arr2.map(iteratee));

  const intersectionList: T[] = [];
  const checkedSet = new Set();

  for (const item of arr1) {
    const appliedIterateeItem = iteratee(item);

    if (!checkedSet.has(appliedIterateeItem) && set.has(appliedIterateeItem)) {
      intersectionList.push(item);
      checkedSet.add(appliedIterateeItem);
    }
  }

  return intersectionList;
};
```

고민을 해보니 comparator 방식이라면 2중 for문 `O(N^2)`이 불가피 할 것 같습니다! break문을 하더라도 배열 길이가 길고 최악의 경우 성능상 안좋을 확률이 높습니다.

uniq와 같이 interatee 형태로 변경하면 `O(n+m)` 형태로 시간복잡도를 줄여볼 수 있을 것 같습니다 !

checked를 통해 중복 아이템을 제거해주는 아이디어 너무 좋은 것 같은데요!
checked를 사전에 먼저 확인 후에 다음 로직을 진행하는게 더 효과적이라고 생각했습니다 👍

기존 코드에서도 comparator를 먼저 실행 후에 checked를 검증하면 리소스가 더욱 클 것 같습니다

2024-06-19 15:06 UTC, ssi02014 commented
@Sangminnn es-toolkit의 경우에도 아래와 같은 방식으로 작성되어 있습니다.
하지만 아래의 경우에는 checked set이 없기 때문에 중복 데이터가 포함됩니다.
```ts
export function intersectionBy<T, U>(firstArr: readonly T[], secondArr: readonly T[], mapper: (item: T) => U): T[] {
  const mappedSecondSet = new Set(secondArr.map(mapper));
  return firstArr.filter(item => mappedSecondSet.has(mapper(item)));
}
```

2024-06-19 15:48 UTC, Sangminnn commented
@ssi02014 좋은 의견 감사합니다! 저 역시도 고민하다보니 comparator 라는 틀 안에서는 불가피하게 높은 시간 복잡도를 가질것으로 보여 제안해주신 방법으로 복잡도를 낮추는게 더 좋아보이네요! 👍 comparator -> iteratee 방식으로 변경해서 적용해보겠습니다! 🫡 

추가적으로 저 역시도 es-toolkit도 한번 둘러보았고 해당 방식으로 동작함을 인지했었는데요! 

개인적으로는 중복을 제거해주는 기능도 효용성이 있어보이기도 하고 두가지 방식 다 각자의 기능이 있다보니 

1. 둘을 별도의 함수로 분리
2. 옵션을 가지고 on/off 할 수 있도록 적용

요런 방식으로 두가지를 모두 살리는 방향으로 가보면 어떨까 생각이 드네요! 😄 

항상 좋은 의견 감사합니다! 👍

2024-06-19 15:51 UTC, ssi02014 commented
감사합니다 👍  옵션을 많이 가져가는 것보다 1번 방향이 좋아보이네요!
`intersection` -> 기본(중복 미포함)
`intersectionWithDuplicates` -> 중복 포함

2024-06-19 15:52 UTC, Sangminnn commented
저도 말씀주신 부분에 공감합니다! 이 부분은 의견 주신 부분 반영해서 함수 분리하도록하겠습니다! 😄 
저야말로 감사합니다! 👍

2024-06-20 06:31 UTC, ssi02014 commented on packages/utils/src/array/index.ts
> +export * from './intersectionWithDuplicate';
오타가 있는 것 같습니다! 마지막에 "s"가 빠져 있네요!

2024-06-20 06:31 UTC, ssi02014 commented on packages/utils/src/array/intersection/intersection.spec.ts
> +describe('intersection', () => {
intersectionWithDuplicate 로 변경되어야 할 것 같습니다!

2024-06-20 06:59 UTC, Sangminnn commented on packages/utils/src/array/index.ts
> +export * from './intersectionWithDuplicate';
@ssi02014 헉 감사합니다! 수정하고서 저장을 안눌렀네요 .. 😂

2024-06-20 07:25 UTC, ssi02014 approved these changes
LGTM

2024-06-20 07:26 UTC, merged

2024-06-20 07:26 UTC, ssi02014 commented
@Sangminnn 억.. changesetlog를 추가하지 못했네요..😭

2024-06-20 07:28 UTC, Sangminnn commented
@ssi02014 헛 괜찮습니다 ! 😂  보통 저는 이 페이지 내에서 상단의 

[Click here if you're a maintainer who wants to add a changeset to this PR](https://github.com/Sangminnn/modern-kit/new/feat/intersection?filename=.changeset/hungry-pans-press.md&value=---%0A%22%40modern-kit%2Fdocs%22%3A%20patch%0A%22%40modern-kit%2Futils%22%3A%20patch%0A---%0A%0Afeat(utils)%3A%20intersection%20%ED%95%A8%EC%88%98%20%EC%9E%91%EC%97%85%20%EC%99%84%EB%A3%8C%0A)

를 통해 추가하고있었는데요! 현재 페이지에서 동일하게 수행할 수 있는걸까요 ?? (경험이 없어 여쭙습니다! 🙇 )

2024-06-20 07:30 UTC, ssi02014 commented
@Sangminnn 제가 우선 추가해놓겠습니다 :) 다른 PR에서 병합하고 CHANGELOG에서 조금 수정하면 될 것 같습니다

2024-06-20 07:31 UTC, Sangminnn commented
@ssi02014 감사합니다! 👍 🙇