Feat(utils): isSubset
modern-agile-team/modern-kit pull request #309
Opened 2024-07-06 13:01 UTC by beberiche

## Overview

Issue: #306

두번째 인자로 주어지는 배열의 모든 요소를 첫번째 인자의 배열이 완전히 포함하는지(부분집합) 에 대한 여부 `boolean` 를 반환합니다.

배열 요소의 타입이 참조형인 경우, 깊은 비교를 진행하며, `iteratee` 함수 인자를 정의하여 비교항목을 설정하는 것이 가능합니다.

## 고민점 1. (배열요소가 참조형인 경우 부분집합의 정의)
예를들어, `[{1:1, 2:2}, {3:3, 4:4}]` 과 `[{2:2}]` 의 경우에 대해 `{2:2}` 는 `{1:1, 2:2}` 의 부분집합이라고 볼 수 있냐는 것 입니다.

결과적으로 저는 **부분집합이 아니라고 판단했습니다.** 참조형 역시 여러 값이 모인 하나의 집합이라고 볼 수 있으며, 객체 입장으로 바라보았을 때`{2:2}`, `{1:1, 2:2}` 는 전혀 다른 구조를 가지므로 부분집합 관계라 정의하기 어렵다고 해석했습니다.

## 고민점 2. (시간복잡도)
위의 정의에 대해, 참조형 요소가 서로 완전 일치하는지 확인하기 위해서는 `깊은 비교` 가 필요합니다. 다만, 객체 내부의 객체, 또 내부의 객체 등 객체의 깊이가 깊을 수록, 시간복잡도는 한없이 증가한다는 문제가 있습니다. 

이에 대해 크게 2가지는 해결안을 모색했습니다.

- 깊이에 상관없이 참조형 요소의 모든 항목을 비교한다.
  - 장점 : 깊이에 상관없이 부분집합 여부를 확인할 수 있다.
  - 단점 : 객체의 수가 많고, 깊이가 깊다면 시간복잡도가 매우 커진다. `O(N*M*d)`
- 깊이가 2보다 미만인 참조형 요소만 인자로 반영되도록 한다.
  - 장점 : 빠른 비교가 가능하다.
  - 단점 : 깊이가 2보다 큰 객체 요소는 부분집합 여부를 확인할 수 없다.

현재 구현된 `isSubset()` 함수는 **깊이에 상관없이 참조형 요소의 모든 항목을 비교하는** 형태로 로직이 구성했습니다. 이미 라이브러리 내에 `deepEqual` 이 구현되어 있기도 했고, 이왕이면 대부분의 케이스를 반영할 수 있도록 하는 것이 라이브러리 구현에 적합하다고 판단했습니다.

두 해결책 모두 장단점이 명확하기 때문에 이 부분은 메인테이너님의 의견도 한번 들어본 후에 다시 고민해보려고 합니다.

## PR Checklist
- [x] All tests pass.
- [x] All type checks pass.
- [x] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-07-06 13:30 UTC, ssi02014 commented
@beberiche 우선 작업해주셔서 정말 감사합니다 :) 
`고민점1`과 `고민점2` 함께 맞물려있는 것 같은데 isSubset함수에서 참조형일 때 이것이 부분집합인지 판단하는 책임은 온전히 사용자에게 위임했으면 합니다. 

이슈의 코멘트로 남긴 예제처럼 부분 집합 임을 결정하는건  `id`만 사용 할 수 있게 사용자가 직접 선택하는 것입니다.
```ts
const arr1 = [{ id: 1, name: 'mj'}, { id: 2 }, {id: 3}];
const arr2 = [{ id: 1}, { id: 2, name: 'gromit' }];

isSubset(arr1, arr2, (item) => item.id); // true
```
`{ id: 1, name: 'mj'}`와 `{ id: 1}`를 같다고 판단할 수 있냐?의 문제는 결국 사용자가 직접 결정할 수 있기 때문에 더이상의 문제가 되지 않습니다. 

또한, 이렇게 될 경우 우리는 참조형일 때 굳이 `깊은 비교`를 하지 않아도 되며, 따라서 현재의 시간복잡도에 대한 고민점도 해결이 가능합니다.

만약, 깊은 중첩 객체 혹은 배열의 케이스에는 `JSON.strinify`와 같은 함수를 이용 할 수 있습니다.

```ts
const arr1 = [{ id: 1, info: { address: 'seou' }}, { id: 2, info: { address: 'busan' }}];
const arr2 = [{ id: 2, info: { address: 'busan' }}];

isSubset(arr1, arr2, (item) => JSON.strinify(item));
```

또는 iteratee의 반환값을 특정해서 지정해도 됩니다. ex: `(item) => ({ id: item.id, address: item.info.address}))`
(하지만, 사실 실제 개발을 할 때 이런 중첩 객체 혹은 중첩 배열에 대한 부분 집합 비교는 흔하지는 않을 거라고 생각합니다..!)

제 의견을 정리하자면, 아래와 같습니다.
1. 기본적으로 `원시값`에 대한 비교를 한다.
2. 참조형과 같은 케이스는 iteratee를 통해 사용자가 직접 부분 집합을 판단할 수 있게 책임을 위임한다.

2024-07-06 13:39 UTC, beberiche commented
@ssi02014 
너무 깊게 고민하고 있었나봅니다!
말씀해주신 수정사항에 맞춰 다시 올리겠습니다!

2024-07-07 14:26 UTC, beberiche commented
@ssi02014 
코드 수정해서 다시 올렸습니다.

2024-07-07 15:55 UTC, ssi02014 requested changes
여러 면에서 검토하느라 리뷰를 늦은 밤에 남기는 점 양해부탁드립니다. 🙏

**기존에 있던 `difference` 함수를 `재사용`해서 구현하는 방향으로 수정되면 좋을 것 같습니다.**

저는 이런 방향성을 위해 간단하지만 [difference의 성능 개선 작업](https://github.com/modern-agile-team/modern-kit/pull/313)을 진행하였습니다. (즉, 최신 main 브랜치와 싱크를 맞춰주세요!)
  - modern-kit의 difference는 lodash의 같은 기능인 differenceBy보다 약 `1.8~2배`가량 빠릅니다.

즉, 아래와 같이 변경을 요청드립니다 :) 
```ts 
const isSubset = <T, U>(
  superset: T[] | readonly T[],
  subset: T[] | readonly T[],
  iteratee?: (item: T) => U
) => {
  return difference(subset, superset, iteratee).length === 0;
};
```
1. 부분집합을 검증하는 의미에서 `superset`, `subset` 으로 인자의 네이밍 변경
2. `superset`, `subset`의 타입을 다른 함수들과 컨벤션을 맞추기 위해 `T[] | readonly T[]` 로 변경
3. `difference` 재사용
4. `문서` 및 `테스트 코드 변수` 네이밍 변경

### 성능 테스트
실제로 제안주신 코드(`isSubsetDefault`)와 difference를 활용한 isSubset 코드(`isSubsetWithDifference`)의 성능 차이는 크게 없습니다.
성능 테스트 실행 할 때마다 결과가 다릅니다. 따라서 이정도 차이는 크게 신경쓰지 않아도 됩니다.
![스크린샷 2024-07-08 오전 12 52 46](https://github.com/modern-agile-team/modern-kit/assets/64779472/4607b6a3-032f-49d0-b1ef-430c98f8cd5d)

![스크린샷 2024-07-08 오전 12 54 06](https://github.com/modern-agile-team/modern-kit/assets/64779472/30a570bf-ef51-4dfc-b1b5-73a482f6c87e)

![스크린샷 2024-07-08 오전 12 54 27](https://github.com/modern-agile-team/modern-kit/assets/64779472/0f693406-5f5b-4a74-a080-0fb4962fa784)

2024-07-07 16:06 UTC, ssi02014 commented on packages/utils/src/validator/isSubset/isSubset.spec.ts
> +});
- 함수 설명을 `it()` 함수에 맞게 변경합니다.
- it과 test는 동일한 기능을 하지만 이름이 서로 다르기 때문에 테스트 설명이 다르게 작성되어야 합니다.
  - https://stackoverflow.com/questions/45778192/what-is-the-difference-between-it-and-test-in-jest

```ts
import { isSubset } from '.';

describe('isSubset', () => {
  it('should return true if the subsetArray is a subset of the superset', () => {
    // 네이밍 변경
    const superset = [1, 2, 3, 4];
    const subset1 = [1, 3];
    const subset2 = [1, 5];
    
    // ...
  });

  it('should return the correct result if the types are different between comparison elements', () => {
    // ...
  });

  it('should handle elements of type array correctly', () => {
    expect(isSubset(superset, subset1, (arr) => arr[2])).toBeTruthy(); // (*) iteratee인자를 arr로 변경해주세요.
    // ...
  });

  it('should handle elements of type reference correctly', () => {
    // ...
  });
});
```

2024-07-08 05:16 UTC, beberiche commented
@ssi02014 
피드백 사항에 맞게 업데이트하여 다시 올렸습니다.

2024-07-08 05:26 UTC, ssi02014 commented on packages/utils/src/validator/isSubset/index.ts
> +};
```suggestion
import { difference } from '../../array';

export const isSubset = <T, U>(
  superset: T[] | readonly T[],
  subset: T[] | readonly T[],
  iteratee?: (item: T) => U
) => {
  return difference(subset, superset, iteratee).length === 0;
};
```

2024-07-08 05:26 UTC, ssi02014 commented on docs/docs/utils/validator/isSubset.md
> +) => boolean;
```suggestion
const isSubset = <T, U>(
  superset: T[] | readonly T[],
  subset: T[] | readonly T[],
  iteratee?: (item: T) => U
) => boolean;
```

2024-07-08 05:28 UTC, ssi02014 commented on docs/docs/utils/validator/isSubset.md
> +배열 요소의 타입이 참조형인 경우, `iteratee` 함수 인자를 정의하여 비교항목을 설정하는 것이 가능합니다.
```suggestion
두 번째 인자로 주어지는 배열의 모든 요소를 첫 번째 인자의 배열이 완전히 포함하는지(부분집합) 여부를 `boolean`으로 반환합니다.

배열 요소의 타입이 참조형인 경우, iteratee 함수 인자를 정의하여 비교 항목을 설정하는 것이 가능합니다.
```

2024-07-08 05:29 UTC, ssi02014 commented on docs/docs/utils/validator/isSubset.md
> +console.log(isSubset(superset, subset2)); // false
```suggestion
isSubset(superset, subset1); // true
isSubset(superset, subset2); // false
```

2024-07-08 05:29 UTC, ssi02014 commented on docs/docs/utils/validator/isSubset.md
> +console.log(isSubset(superset, subset2)); // false
```suggestion
import { isSubset } from '@modern-kit/utils';

const superset = ['1', 2, 3, 4];
const subset1 = ['1', 2, 3];
const subset2 = [1, '2', 3];

isSubset(superset, subset1); // true
isSubset(superset, subset2); // false
```

2024-07-08 05:30 UTC, ssi02014 commented on docs/docs/utils/validator/isSubset.md
> +isSubset(superset, subset2, (obj) => obj.name); // true
```suggestion
isSubset(superset, subset1); // false, 요소가 참조형(객체)이므로, 주소값이 달라 false를 반환한다
isSubset(superset, subset1, (obj) => JSON.stringify(obj)); // true
isSubset(superset, subset2, (obj) => JSON.stringify(obj)); // false
isSubset(superset, subset2, (obj) => obj.name); // true
```
```

2024-07-08 05:32 UTC, ssi02014 approved these changes
작업하시느라 고생하셨습니다 🤗

2024-07-08 05:39 UTC, merged