feat(utils): range 함수 추가 완료
modern-agile-team/modern-kit pull request #344
Opened 2024-07-17 13:29 UTC by Sangminnn

## Overview

Issue: #282 

`주어진 범위 내의 숫자 배열`을 생성해줍니다.

`인자가 하나`만 들어오는 경우 `1부터 해당 값까지의 숫자 배열을 생성`해줍니다.

`세 번째 인자`로 `간격`을 명시해주면, 시작값부터 끝값까지의 숫자 중 `시작값부터 해당 간격만큼 떨어진 값들을 포함하는 배열을 생성`합니다.

## PR Checklist
- [x] All tests pass.
- [x] All type checks pass.
- [x] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-07-17 13:30 UTC, Sangminnn commented on packages/utils/src/math/range/index.ts
> +
배열의 공간을 미리 만들어주는 방법을 고민해보았으나, 주어진 스펙에 비해 오버엔지니어링으로 판단하여 간단하게 작성했습니다.

추가적으로 잘못 활용했을 수 있으나 benchmark를 활용하였을때에도 미리 공간을 확보하는 방법이 더 낮은 성능으로 나왔었네요 😂

2024-07-17 13:31 UTC, Sangminnn commented on packages/utils/src/math/range/index.ts
> +
일반적으로 -0은 들어오지 않을 것으로 예상되지만 0과 -0 모두 체크할 수 있도록 아래와 같이 사용했습니다.

2024-07-17 13:35 UTC, Sangminnn commented on packages/utils/src/math/range/index.ts
> +  const result = [];
배열의 공간을 미리 만들어주는 방법을 고민해보았으나, 주어진 스펙에 비해 오버엔지니어링으로 판단하여 간단하게 작성했습니다.

추가적으로 잘못 활용했을 수 있으나 benchmark를 활용하였을때에도 미리 공간을 확보하는 방법이 더 낮은 성능으로 나왔었네요 😂

2024-07-17 13:35 UTC, Sangminnn commented on packages/utils/src/math/range/index.ts
> +  if (Object.is(step, 0) || Object.is(step, -0)) {
일반적으로 -0은 들어오지 않을 것으로 예상되지만 0과 -0 모두 방어할 수 있도록 아래와 같이 사용했습니다.

2024-07-17 15:23 UTC, ssi02014 commented on packages/utils/src/math/range/index.ts
> +export function range(startOrEnd: number, end?: number, step?: number) {
```suggestion
export function range(start: number, end?: number, step?: number) {
```
함수 오버로딩 네이밍을 맞추는게 적절해보입니다 :)

2024-07-17 15:28 UTC, ssi02014 commented on packages/utils/src/math/range/index.ts
> +  }
```suggestion
  if (isNil(end)) {
    getRangeValue(0, start);
  }
```
시작을 기본 값이 1이아닌 0이 적절한 것 같습니다! 
파이썬의 경우에도 range의 결과는  아래와 같습니다

```python
print(list(range(5))); // [0, 1, 2, 3, 4]
```

2024-07-17 15:36 UTC, ssi02014 commented on packages/utils/src/math/range/index.ts
> +  }
```suggestion
  if (!Number.isInteger(step) || Object.is(step, 0)) {
    throw new Error('The step value must be a non-zero integer.');
  }
```
- `-0`은 너무 엣지케이스라 0만 처리해도 좋을 것 같습니다 :) 

```python
print(list(range(10, 5, 0))); # ValueError
```

2024-07-17 15:52 UTC, ssi02014 requested changes
@Sangminnn 기본적으로 저희가 제공하고자 하는 range가 python의 range와 동일하게 동작하면 어떨까 제안드려봅니다 ! 🤗
따라서, 기존 코드를 약간 개선 후 제안드리는 코드는 아래와 같은데 추가적인 좋은 의견 말씀주시면 감사드립니다 !! 
```ts
const getRangeValues = (start: number, end: number, step = 1) => {
  const length = Math.max(Math.ceil((end - start) / step), 0);
  const result = new Array(length);

  for (let i = 0; i < length; i++) {
    result[i] = start + i * step;
  }

  return result;
};

export function range(end: number): number[];
export function range(start: number, end: number): number[];
export function range(start: number, end: number, step: number): number[];
export function range(start: number, end?: number, step?: number) {
  if (isNil(end)) {
    return getRangeValue(0, start);
  }

  if (isNil(step)) {
    step = 1;
  }

  if (!Number.isInteger(step) || Object.is(step, 0)) {
    throw new Error('The step value must be a non-zero integer.');
  }

  return getRangeValues(start, end, step);
}
```

2024-07-17 15:57 UTC, ssi02014 commented on packages/utils/src/math/range/index.ts
> +};
현재 코드는 start가 end보다 클 경우의 처리를 못한다는 점과 (즉, step이 음수 일 때도 처리가 안됌 🥹)
`value <= end` 값으로 인해 end값이 포함된다는 이슈가 있는 것 같습니다. getRangeValue가 아래와 같이 변경되면 좋을 것 같습니다.

```ts
const getRangeValue = (start: number, end: number, step = 1) => {
  const length = Math.max(Math.ceil((end - start) / step), 0);
  const result = new Array(length);

  for (let i = 0; i < length; i++) {
    result[i] = start + i * step;
  }

  return result;
};
```

2024-07-17 16:02 UTC, ssi02014 commented
@Sangminnn 
제가 기대하는 케이스는 대충 아래와 같습니다 !! 
```ts
expect(range(5)).toEqual([0, 1, 2, 3, 4]); // end 존재

expect(range(5, 10)).toEqual([5, 6, 7, 8, 9]); // start, end 존재

expect(range(5, 10, 2)).toEqual([5, 7, 9]); // start, end, step 존재

expect(range(10, 5, 1)).toEqual([]); // start > end, step 양수

expect(range(10, 5, -1)).toEqual([10, 9, 8, 7, 6]); // start > end, step 음수

expect(range(-10, -5, 1)).toEqual([-10, -9, -8, -7, -6]); // start, end 음수

expect(range(5, 10, 0)).toEqual([]); // Error, 0은 에러

expect(range(5, 10, 1.1)).toEqual([]); // Error, 실수는 에러
```

## python range
```python
print(list(range(5))) # [0, 1, 2, 3, 4]

print(list(range(5, 10))) # [5, 6, 7, 8, 9]

print(list(range(5, 10, 2))) # [5, 7, 9]

print(list(range(10, 5, 1))) # []

print(list(range(10, 5, -1))) # [10, 9, 8, 7, 6]

print(list(range(-10, -5, 1))) # [-10, -9, -8, -7, -6]

print(list(range(5, 10, 0))) # ValueError

print(list(range(5, 10, 0.1))) # ValueError
```

2024-07-18 14:19 UTC, Sangminnn commented on packages/utils/src/math/range/index.ts
> +  const result = [];
@ssi02014 꼼꼼하게 봐주셔서 감사합니다! 어떤 부분에서 성능이 제대로 나오지 않았는지 다시 확인해보았는데, 제가 테스트했던 방법은 정확히 알고 사용하지 않은 Array.from을 사용했었네요! 실제로 이렇게 할 경우 초기화 단계를 거치기때문에 성능적으로 좋지 않아 lodash/range보다 낮은 성능을 보였습니다!

초기화 단계를 거치지 않고 공간을 만들어주는 new Array를 사용하면 평균적으로 약 1.5배정도 빠른것으로 확인되었습니다! 👍

2024-07-18 14:20 UTC, Sangminnn commented
@ssi02014 감사합니다! 예시케이스를 보고 너무 단편적으로 생각해버렸네요 😂 
말씀주신 부분에 공감해서 전반적으로 수정하면서 0부터 시작하는 부분과 음수의 step도 지원할 수 있도록 수정하도록 하겠습니다! 🫡

2024-07-18 15:50 UTC, Sangminnn commented
@ssi02014 더 좋은 방법이 있을지 고민해보았는데 제안해주신 것처럼 불필요한 조건문을 제거할 수 있으면서 원하는 케이스를 구현할 수 있도록 new Array의 length를 Math.max를 통해 해결하는 방법이 가장 좋아보이네요!
좋은 의견 주셔서 많이 배워갑니다! 👍 🙇 

벤치마크도 큰 수치는 아니지만 미약하나마 빠른 속도를 보여 추가해두었습니다!

2024-07-19 03:56 UTC, ssi02014 approved these changes

2024-07-19 03:59 UTC, ssi02014 commented on docs/docs/utils/math/range.md
> +function range(start: number, end?: number, step?: number): number[]
```suggestion
function range(end: number): number[];
function range(start: number, end: number): number[];
function range(start: number, end: number, step: number): number[];
```

2024-07-19 04:00 UTC, ssi02014 commented on docs/docs/utils/math/range.md
> +const result4 = range(-10, -5, 1); // [-10, -9, -8, -7, -6]
```suggestion
import { range } from '@modern-kit/utils';

const result1 = range(5); // [0, 1, 2, 3, 4]
const result2 = range(1, 6); // [1, 2, 3, 4, 5]
const result3 = range(1, 6, 2); // [1, 3, 5]
const result4 = range(-10, -5, 1); // [-10, -9, -8, -7, -6]
const result5 = range(10, 5, -1); // [10, 9, 8, 7, 6]
```

2024-07-19 04:06 UTC, ssi02014 commented on docs/docs/utils/math/range.md
> +`세 번째 인자`로 `간격`을 명시해주면, 시작값부터 끝값까지의 숫자 중 `시작값부터 해당 간격만큼 떨어진 값들을 포함하는 배열을 생성`합니다.
```suggestion
`주어진 범위 내의 숫자 배열`을 생성합니다.

`하나의 인자`만 들어오는 경우 `0부터 해당 값 전까지의 숫자 배열`을 생성합니다.

`두 개의 인자`가 들어오는 경우 `첫 번째 인자값을 포함`하여 `두 번째 인자값 전까지의 숫자 배열`을 생성하며, `음수` 사이의 간격도 구할 수 있습니다.

`세 번째 인자`로 `간격(step)`을 명시해주면, 첫 번째 인자값부터 두 번째 인자값 전까지의 숫자 중 `주어진 간격만큼 떨어진 값들을 포함하는 배열을 생성`합니다.
```

2024-07-19 04:08 UTC, ssi02014 commented
@Sangminnn 문서만 몇 가지 수정하고 어프했습니다 고생하셨습니다 :) !

2024-07-19 04:15 UTC, merged

2024-07-19 04:15 UTC, Sangminnn commented
@ssi02014 아고 항상 놓친부분 챙겨주셔서 너무 감사합니다! 🙇