feat(utils) mapValues 유틸 함수 추가
modern-agile-team/modern-kit pull request #368
Opened 2024-07-24 16:56 UTC by Gaic4o

## Overview

Issue: #320 

`mapValues` 주어진 객체의 각 값에 대해 제공된 변환 함수를 호출하여 새 객체를 생성하는 함수입니다.

기존에 `mapValues` 함수를 구현할 때 `object` 매개변수 타입에 심볼 타입을 추가하여 작업을 진행했었습니다.
심볼 타입을 사용하면 심볼 `Object.getOwnPropertySymbols` 같은 메서드를 사용해야 하는데, 추가적으로 문자열 키만을 처리할 떄 보다 조건 연산 코드가 생기고, 대부분 mapValues 함수에서 심볼 타입을 드물게 사용하는 것 같아, 
`object` 타입에서 심볼 타입을 제외하고 string과 number 타입만 포함해서 `mapValues` 함수를 구현했습니다. 

심볼 타입을 제외하는 게 더 나은 접근일지 이 부분 메인테이너 분의 피드백을 받아보고 싶습니다. 

![스크린샷 2024-07-25 오전 1 15 36](https://github.com/user-attachments/assets/df5b1433-beb0-4668-8146-01e350f3fccd)

## PR Checklist
- [x] All tests pass.
- [x] All type checks pass.
- [x] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-07-25 16:02 UTC, ssi02014 requested changes
1. 심볼을 다루는 케이스는 흔하지 않기 때문에 `symbol`에 대해서 다루지 않아도 될 것 같습니다
2. 기본적인 로직은 모두 좋은 것 같습니다 🤗 타입을 아래와 같이 수정을 제안드려볼까 합니다.
```ts
import { hasProperty } from '../../validator/hasProperty';

export function mapValues<T extends Record<PropertyKey, any>, V>(
  object: T,
  iteratee: (iterateData: { key: keyof T; value: T[keyof T]; object: T }) => V
): Record<keyof T, V> {
  const result = {} as Record<keyof T, V>;

  for (const key in object) {
    if (hasProperty(object, key)) {
      result[key] = iteratee({ key, value: object[key], object });
    }
  }
  return result;
}
```
3.`Object.prototype.hasOwnProperty.call(object, key)` 의 역할을 하는 로직이 기존 `hasProperty`가 있습니다. 해당 함수를 import해서 사용하면 밴치마킹 테스트 결과가 기존보다 약간 안좋게 나오는데, 사실상 큰 차이가 없다고 생각합니다. 해당 로직을 재사용하는 방향으로 제안드려봅니다 :)

2024-07-28 08:24 UTC, Gaic4o commented
> 1. 심볼을 다루는 케이스는 흔하지 않기 때문에 `symbol`에 대해서 다루지 않아도 될 것 같습니다
> 2. 기본적인 로직은 모두 좋은 것 같습니다 🤗 타입을 아래와 같이 수정을 제안드려볼까 합니다.
> 
> ```ts
> import { hasProperty } from '../../validator';
> 
> export function mapValues<T extends Record<PropertyKey, any>, V>(
>   object: T,
>   iteratee: (iterateData: { key: keyof T; value: T[keyof T]; object: T }) => V
> ): Record<keyof T, V> {
>   const result = {} as Record<keyof T, V>;
> 
>   for (const key in object) {
>     if (hasProperty(object, key)) {
>       result[key] = iteratee({ key, value: object[key], object });
>     }
>   }
>   return result;
> }
> ```
> 
> 3.`Object.prototype.hasOwnProperty.call(object, key)` 의 역할을 하는 로직이 기존 `hasProperty`가 있습니다. 해당 함수를 import해서 사용하면 밴치마킹 테스트 결과가 기존보다 약간 안좋게 나오는데, 사실상 큰 차이가 없다고 생각합니다. 해당 로직을 재사용하는 방향으로 제안드려봅니다 :)

좋습니다!!

2024-07-28 08:34 UTC, ssi02014 approved these changes
고생하셨습니다 너무 좋은 함수라고 생각합니다 🤗

2024-07-28 08:34 UTC, ssi02014 commented on packages/utils/src/object/mapValues/mapValues.bench.ts
> +  });
```suggestion
  bench('lodash/mapValues', () => {
    mapValuesLodash(obj, iteratee);
  });
```

2024-07-28 08:35 UTC, ssi02014 commented on packages/utils/src/object/mapValues/mapValues.bench.ts
> +  };
```suggestion
import { bench, describe } from 'vitest';
import { mapValues as mapValuesLodash } from 'lodash-es';
import { mapValues } from '.';

describe('mapValues', () => {
  const obj = {
    a: 1,
    b: 2,
    c: 3,
    d: 4,
    e: 5,
    f: 6,
    g: 7,
  };
```

2024-07-28 08:35 UTC, ssi02014 commented on packages/utils/src/object/mapValues/index.ts
> + */
```suggestion
import { hasProperty } from '../../validator';

/**
 * @description 주어진 객체의 각 값에 대해 제공된 변환 함수를 호출하여 새 객체를 생성하는 함수입니다.
 *
 * @template T - 원본 객체 값의 유형입니다.
 * @template R - 반환할 새 객체 값의 유형입니다.
 * @param {T} object - 순회할 원본 객체입니다.
 * @param {(iterateData: { key: keyof T; value: T[keyof T]; object: T }) => V} iteratee - 객체의 각 값에 대해 호출할 변환 함수입니다.
 * @returns {Record<keyof T, V>} 변환 함수의 결과를 포함하는 새 객체를 반환합니다.
 */
```

2024-07-28 08:40 UTC, merged