feat(utils): serialize 유틸함수 추가 완료
modern-agile-team/modern-kit pull request #375
Opened 2024-07-27 16:02 UTC by Sangminnn

## Overview

Issue: #370 

객체로 들어온 값을 쿼리 파라미터로 사용할 수 있도록 직렬화해주는 유틸함수입니다.

## PR Checklist
- [ ] All tests pass.
- [ ] All type checks pass.
- [ ] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-07-27 16:05 UTC, Sangminnn commented on packages/utils/src/string/serialize/index.ts
> +
추가적으로 쿼리 파라미터로서 사용하기 편하도록 제공하는 유틸함수이기때문에 인코딩 여부에 대한 옵션을 받는 것은 어떨지도 고민이네요! 이 부분에 대해서 좋은 의견있으시다면 편하게 말씀주시면 감사드리겠습니다! 😄 

1. 간단한 인코딩 방식을 on/off 로 제공 (ex. encodeURIComponent)
2. 인코딩에 대한 함수를 받아서 이를 그대로 적용해주는 방식

만약 적용한다면 간단하게는 요런 방식이 떠오르네요 😂

2024-07-27 18:13 UTC, ssi02014 commented on packages/utils/src/string/serialize/index.ts
> +};
## isValidValue
```ts
// 타입 제네릭 사용
const isValidValue = <T>(value: T, options: SerializeOptions = {}) => {
  const { skipNull = true, skipEmptyString = true } = options;

  return !(skipNull && value == null) && !(skipEmptyString && value === '');
};
```
- query-string의 stringify는 기본적으로 `undefined`를 무시하는 것 같은데,저희는 `URLSearchParams().toString()` 과 같이 skip 옵션이 없다면 `undefined`를 그냥 함께 포함하는게 어떨까요 !?
- 아니면 `skipUndefined` 옵션을 추가해 이를 핸들링하는 것도 좋습니다..!

<br /> 

## serializeKeyValue
```ts
// 타입 제네릭 사용
const serializeKeyValue = <T>(
  key: string, // for...in문의 key의 타입은 Extract<keyof T, string>이기 때문에 string
  value: T, // 제네릭 적용
  options: SerializeOptions
) => {
  if (!isValidValue(value, options)) return '';

  return `${key}=${value}`;
};
```
- boolean, string 두 타입으로 반환하기보다 타입이 `문자열로 통일`하면 좋을 것 같습니다!

<br />

## serializeArray
```ts
const serializeArray = <T>(
  key: string,
  array: T[] | readonly T[], //제네릭 적용
  options: SerializeOptions
) => {
  const values = [];

  for (const value of array) {
    const serializedValue = serializeKeyValue(key, value, options);

    if (serializedValue) {
      values.push(serializedValue);
    }
  }

  return values.join('&');
};
```
- map.filite.join (3N)보다 `for...of`문 한번으로 끝내면 좀 더 효율적일 것 같습니다!

<br />

## serialize
```ts
// Record타입을 확장한 제네릭 T 사용
export const serialize = <T extends Record<PropertyKey, any>>(
  obj: T,
  options: SerializeOptions = {}
) => {
  const result = [];

  for (const key in obj) {
    const value = obj[key];

    if (isArray(value)) {
      const serializedArray = serializeArray(key, value, options);

      if (serializedArray) result.push(serializedArray);
    } else {
      const serializedValue = serializeKeyValue(key, value, options);

      if (serializedValue) result.push(serializedValue);
    }
  }

  return result.join('&');
};
```
- `entries`보다 효율성이 높은 `for...in`문을 활용하면 어떨까요!?
- `entries().map().filter().join()` 연속된 메서드 체이닝보다 효율적입니다!

<br />

## 밴치마크 결과
- 변경된 로직이 `1.5배 가량` 더 향상된 성능을 갖습니다!

![스크린샷 2024-07-28 오전 3 02 43](https://github.com/user-attachments/assets/e63dfe2e-f5c0-48de-b7a0-258ea7d59afe)

2024-07-27 18:14 UTC, ssi02014 requested changes
고생하셨습니다 조금 더 성능과 타입을 개선한 제 의견을 코멘트로 남겼씁니다 :)

2024-07-27 18:18 UTC, ssi02014 commented on packages/utils/src/string/serialize/index.ts
> +
@Sangminnn  serialize에 인코딩 기능을 포함하기 보다 현재 serialize 옵션으로는 `skip`과 관련된 옵션만 제공하는게 좋지 않을까 싶습니다! 🤔

2024-07-27 18:54 UTC, ssi02014 commented on packages/utils/src/string/serialize/index.ts
> +};
약간 의아한 점은 hasProperty라고 기존 `Object.prototype.hasOwnProperty.call(obj, key)`과 동일한 기능을 하는 모듈이 존재하는데 해당 함수를 사용하면 테스트 성능이 떨어지네요;

### hasProperty 사용
- 약 1.2배 성능 개선
![스크린샷 2024-07-28 오전 3 52 46](https://github.com/user-attachments/assets/197de2ff-0304-430d-b8ad-757866c64000)

### Object.prototype.hasOwnProperty.call 사용
![스크린샷 2024-07-28 오전 3 53 20](https://github.com/user-attachments/assets/5dad06d3-c5e8-433b-86b7-16a3d66bf6fc)

빌트인 함수를 사용하는지, 외부 모듈을 사용하는지에 따라 테스트 환경에 영향이 있는 것 같지만 실제 두 로직은 동일하기 때문에 `1.5배` 가량 더 성능 개선이 됐다고 보는게 맞을 것 같습니다

2024-07-27 19:09 UTC, ssi02014 commented on packages/utils/src/string/serialize/index.ts
> +};
flatten과 같은 js-doc가 추가되면 좋을 것 같습니다 🤗

2024-07-28 05:37 UTC, Sangminnn commented on packages/utils/src/string/serialize/index.ts
> +};
@ssi02014 자세히 확인해주셔서 너무 감사합니다! 🙇 

1. 아무래도 실제 유즈케이스에서는 타 함수와 다르게 간결한 객체가 들어올 것으로 생각하고 내부함수에 대해 제네릭처리와 성능을 크게 고려하지 않고 비교적 간결한 코드로 나타낼 수 있는 함수형의 조합으로 작성했었으나, invalid value에 대해 false로 처리하는 부분이나 기존의 Object.entries를 더 나은 성능의 Keys와 for ... of 의 조합으로 처리하는 방법이 더 좋아보여 수정하도록 하겠습니다! 👍 

2. undefined의 경우 의도적으로 빈 값을 할당하는 것이 아닌 할당되지 않은 상태를 의미한다는 점과 url의 search param에서의 활용을 의도한 해당 함수의 특성에 따라 undefined을 value로 넣어주는 부분이 어색하다고 느껴 자체적으로 핸들링을 통해 허용하지 못하도록 막아두었으나, 해당 옵션을 열어주더라도 실제로 이를 의도적으로 제거하지 않는 케이스는 거의 드물것으로 판단하여 제안주신 것처럼 유저가 선택하여 처리할 수 있도록 옵션에 추가해두겠습니다!

3. 추가적으로 의견주신 js-doc과 내부함수에 대한 분리도 적용해두겠습니다! 


전반적으로 놓친 부분이 많았는데 다방면으로 좋은 의견 주셔서 너무 감사합니다! 👍

2024-07-28 05:43 UTC, ssi02014 commented on packages/utils/src/string/serialize/index.ts
> +};
@Sangminnn 긍정적으로 봐주셔서 감사합니다 :) 작업을 진행해주셔서 감사드립니다!

2024-07-28 06:59 UTC, Sangminnn commented on packages/utils/src/string/serialize/index.ts
> +
일반적으로 search param으로 사용하기때문에 덮는 케이스를 일반적으로 가져가는것으로 보이네요!
요 부분은 의견주신것처럼 추후 파생함수로 풀어가는 방향을 고민해보면 좋을것같습니다! 👍

2024-07-28 07:02 UTC, Sangminnn commented on packages/utils/src/string/serialize/index.ts
> +};
@ssi02014 항상 다양한 관점에서 더 좋은 의견 주셔서 제가 더 감사합니다! :)

2024-07-28 07:05 UTC, ssi02014 commented on packages/utils/src/string/serialize/index.ts
> +}
```suggestion
export function serialize<T extends Record<PropertyKey, any>>(
  obj: T,
  options: SerializeOptions = {}
) {
  const keys = Object.keys(obj);
  let result = '';

  for (const key of keys) {
    const target = obj[key];
    const serializedValue = serializeByType(key, target, options);

    if (serializedValue) {
      result += result ? `&${serializedValue}` : serializedValue;
    }
  }

  return result;
}
```
- object의 타입을 T로 사용합니다.
- const인 상수가 상단에 올라오게끔 수정하였습니다

2024-07-28 07:06 UTC, ssi02014 commented on docs/docs/utils/string/serialize.md
> +) => string
```suggestion
function serialize<T extends Record<PropertyKey, any>>(
  obj: T,
  options?: SerializeOptions
): string;
```

2024-07-28 07:07 UTC, ssi02014 approved these changes

2024-07-28 07:12 UTC, merged