yfeat(utils) mapKeys 유틸 함수 추가
modern-agile-team/modern-kit pull request #395
Opened 2024-08-01 14:55 UTC by Gaic4o

## Overview

Issue: #321 

객체의 key를 iteratee의 결과 값 변환해주는 함수입니다.

## PR Checklist
- [x] All tests pass.
- [x] All type checks pass.
- [x] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-08-01 16:11 UTC, ssi02014 requested changes
작업 감사합니다! 추가적인 의견 남겼습니다! 확인부탁드립니다 ㅎㅎ

2024-08-01 16:11 UTC, ssi02014 commented on packages/utils/src/object/mapKeys/index.ts
> +}
```suggestion
export function mapKeys<
  T extends Record<PropertyKey, any>,
  U extends PropertyKey
>(
  object: T,
  iteratee: (iterateData: { key: keyof T; value: T[keyof T]; object: T }) => U
): Record<U, T[keyof T]> {
  const result = {} as Record<U, T[keyof T]>;

  for (const key in object) {
    if (hasProperty(object, key)) {
      const newKey = iteratee({ key, value: object[key], object });
      result[newKey] = object[key];
    }
  }

  return result;
}
```
- iteratee 함수의 반환 타입을 제네릭(`U`)을 활용해 더욱 타입 추론을 원활하게 할 수 있을 것 같습니다 🤗

2024-08-01 16:11 UTC, ssi02014 commented on packages/utils/src/object/mapKeys/mapKeys.spec.ts
> +  });
```suggestion
  it('should map object keys by appending values to keys', () => {
    const obj = { a: 1, b: 2 } as const;

    const expected = { a1: 1, b2: 2 } as const;

    const result = mapKeys(obj, ({ key, value }) => `${key}${value}`);

    expect(result).toEqual(expected);
  });
```

원활하게 타입 추론을 되는지 확인하기 위해 테스트 코드 작성 시 iteratee를 추출해서 인자로 넣기 보다 그냥 위와 같이 작성하는게 이해하는데 더  원활할 것 같습니다!!

<img width="628" alt="스크린샷 2024-08-02 오전 1 07 51" src="https://github.com/user-attachments/assets/f4162908-7a48-40d7-a3a2-76f88dee9fbe">

2024-08-03 11:52 UTC, Gaic4o commented on packages/utils/src/object/mapKeys/index.ts
> +}
수정 했습니다 감사합니다!

2024-08-03 11:52 UTC, Gaic4o commented on packages/utils/src/object/mapKeys/mapKeys.spec.ts
> +  });
수정했습니다!

2024-08-04 06:02 UTC, ssi02014 approved these changes
작업감사드립니다 :) 고생하셨습니다!

2024-08-04 06:02 UTC, merged