feat(react): useBlockDoubleClick 추가
modern-agile-team/modern-kit pull request #82
Opened 2024-04-29 15:30 UTC by Sangminnn

## Overview

useDebounce는 동일한 이벤트가 중복으로 발생할 경우 이를 적게 호출할 수 있도록 도와줍니다. 또한 이러한 특징을 활용하여 순간적인 중복호출을 방지하는 역할을 하기도 하는데, 이는 시간을 다루는 작업이기에 완벽하게 막아낼 수 없습니다.

이 훅은 특정 Promise동작을 수행하는 동안은 중복호출이 불가능하도록 만들어둔 훅입니다.

## PR Checklist
- [O] All tests pass.
- [O] All type checks pass.
- [O] I have read the Contributing Guide document.
    [Contributing Guide](https://github.com/modern-agile-team/modern-kit/blob/main/.github/CONTRIBUTING.md)

2024-04-29 16:08 UTC, ssi02014 requested changes
@Sangminnn  우선 기여를 위해 PR을 생성해주셔서 감사드립니다! 너무나도 유용한 훅인 것 같습니다...! ☺️
개인적으로 아래와 같은 추가 의견이 있는데 검토해주시면 감사드립니다!

<br />

```tsx
beforeAll(() => { // (*)
  vi.useFakeTimers();
});

afterAll(() => { // (*)
  vi.useFakeTimers();
});

const delay = (time: number) => { /* ... */ };

describe('useBlockDoubleClick', () => {
  it('should block double click', async () => {
    const mockFn = vi.fn(async () => await delay(1000)); // (*) mock 함수를 활용
    const { result } = renderHook(useBlockDoubleClick);

    const { isLoading, blockDoubleClick } = result.current;
    expect(isLoading).toBe(false);

    const onClick = () => blockDoubleClick(mockFn); // (*) mock 함수를 넘김

    const { user } = renderSetup(<button onClick={onClick}>TestButton</button>);

    const button = screen.getByRole('button'); // (*) getByRole 활용

    user.click(button); // (*) fakeTimer와의 이슈로 await제거하고 대신 vi.advanceTimersByTimeAsync(500) 추가
    user.click(button); // (*)

    await vi.advanceTimersByTimeAsync(500); // (*)

    expect(result.current.isLoading).toBe(true);
    expect(mockFn).toBeCalledTimes(1); // (*) mock 함수 활용으로 toBeCalledTimes와 함께 활용

    await vi.advanceTimersByTimeAsync(600); // (*)

    expect(result.current.isLoading).toBe(false); // (*) false 변환 케이스 추가
  });
});
```
- 위와 같이 `isLoading`이 false로 변경되는 케이스도 추가하는 것은 어떨까요? 
- 그런데 현재 `fakeTimer`와 `await userEvent`을 함께 사용하면 timeout이 발생하는 이슈가 있습니다. 대신 `vi.advanceTimersByTimeAsync` 로 우회할 수는 있을 것 같습니다!

![스크린샷 2024-04-30 오전 1 07 46](https://github.com/modern-agile-team/modern-kit/assets/64779472/9bd21d17-3e66-4157-bcca-12939b11522c)

- 추가적으로 blockDoubleClick으로 넘겨주는 함수가 몇 번 호출되었는지가 테스트 주요 포인트이기 때문에 vi.fn을 활용해서 `mockFn`를 생성하고 `toBeCalledTimes`와 함께 활용하는 것은 어떨까요!

2024-04-29 16:12 UTC, ssi02014 commented on packages/react/src/hooks/useBlockDoubleClick/index.ts
> +export default useBlockDoubleClick;
```ts
export useBlockDoubleClick = () => {}
```
useBlockDoubleClick을 `default export`말고 `named export`로 변경해주시면 감사드립니다!

2024-04-30 14:09 UTC, Sangminnn commented
@ssi02014 좋은 의견 감사합니다! 전반적으로 말씀주신 의견과 가이드를 반영하였고, hook의 네이밍만 use(동사)(명사) 의 형태로 작성하는 것이 더 자연스러워보여 이와 같이 네이밍을 변경해두었습니다!

2024-04-30 14:12 UTC, ssi02014 commented
@Sangminnn 수정 감사합니다!! 앗 마지막으로 훅 내부 blockDoubleClick 함수도 네이밍을 수정이 되면 좋을 것 같습니다!!

2024-04-30 14:15 UTC, Sangminnn commented
@ssi02014 감사합니다! 수정과정에서 해당 메서드의 네이밍 변경을 놓쳤네요! 맥락에 맞게 blockMultipleClick으로 메서드명을 수정해두었습니다 :)

2024-04-30 14:20 UTC, ssi02014 approved these changes
기여감사합니다🤗🤗🤗

2024-04-30 14:21 UTC, merged

2024-04-30 15:21 UTC, ssi02014 commented
@Sangminnn 

`@modern-kit/react@1.3.0`이 release 🚀 되었습니다 !
아래 링크에서 추가된 문서를 확인하실 수 있습니다 기여에 감사드립니다! 👍
[useBlockPromiseMultipleClick](https://modern-agile-team.github.io/modern-kit/docs/react/hooks/useBlockPromiseMultipleClick)